import {PGlite} from '../database/node_modules/@electric-sql/pglite/dist/index.js';
import {readFile,readdir} from 'node:fs/promises';
export const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema extensions;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,created_at timestamptz default now(),raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;create schema storage;create table storage.buckets(id text primary key,name text,public boolean);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant all on storage.objects to authenticated;`);
await db.exec('alter default privileges in schema public grant all on tables to anon,authenticated; create role migration_admin nologin createrole bypassrls; grant postgres to migration_admin; create role auth_fixture_owner; alter schema auth owner to auth_fixture_owner; grant usage on schema auth to migration_admin with grant option; set role migration_admin; alter default privileges in schema public grant all on tables to anon,authenticated;');
for(const f of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort()){

 let sql=await readFile('supabase/migrations/'+f,'utf8');sql=sql.replace(/create extension if not exists pgcrypto[^;]*;/gi,'');
 try{await db.exec(sql);console.log('APPLIED',f);}catch(e){console.error('FAILED',f,e.message,e.query?.slice(-1200));throw e;}
}
await db.exec('reset role; grant usage on schema auth to academy_executor; revoke usage on schema auth from migration_admin cascade; grant postgres,academy_executor to migration_admin with inherit false;');
console.log('PASS migrations (fresh baseline applied without SUPERUSER)');
const q=async(s,p=[]) => (await db.query(s,p)).rows;
let checks=0;const assert=(ok,label)=>{if(!ok)throw Error(label);checks++;console.log('PASS',label);};
async function rejects(fn,label){let rejected=false;try{await fn();}catch(e){rejected=true;console.log('REJECTED',e.message);}assert(rejected,label);}
assert((await q("select count(*)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_roles r on r.oid=p.proowner where n.nspname in ('public','academy_private') and p.prosecdef and r.rolname not in ('postgres','academy_executor')"))[0].n===0,'all application security-definer helpers have stable runtime owners');
assert((await q("select count(*)::int n from pg_views where schemaname='public' and viewname ~ '(finance|invoice|payment|payroll|refund|fee_plan|compensation|referral)'"))[0].n===0,'no empty financial compatibility views are installed');
assert((await q("select count(*)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname ~ '(finance|invoice|payment|payroll|refund|discount|referral)'"))[0].n===0,'no financial RPCs or helper functions are installed');
assert((await q("select has_table_privilege('anon','public.branch_owners','SELECT') ok"))[0].ok===false,'hosted default grants do not expose institution owners');
assert((await q("select has_table_privilege('authenticated','public.branch_open_commands','SELECT') ok"))[0].ok===false,'idempotency records remain private despite hosted default grants');
const owner='11111111-1111-4111-8111-111111111111',outsider='22222222-2222-4222-8222-222222222222',teacher='33333333-3333-4333-8333-333333333333';
await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${owner}','owner@example.test',now()),('${outsider}','outsider@example.test',now()),('${teacher}','teacher@example.test',now());`);
async function as(user,branch='',role='authenticated') {await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false),set_config('request.headers',$2,false)",[user,JSON.stringify({'x-academy-branch':branch})]);await db.exec('set role '+role);}
await as(owner);const request=crypto.randomUUID();
const open=async(req,name,slug,org='Academy')=>(await q('select public.open_academy_branch($1,$2,$3,$4,false) result',[req,name,slug,org]))[0].result;
const first=await open(request,'Central','central-campus');assert(first.id===(await open(request,'Central','central-campus')).id,'branch opening is idempotent');
await rejects(()=>open(request,'Changed','changed-campus'),'request reuse with changed input rejected');
const second=await open(crypto.randomUUID(),'North','north-campus');
await as(owner,first.id);
assert((await q('select count(*)::int n from public.programs'))[0].n===4,'selected branch has four starter programmes');
assert((await q('select count(*)::int n from public.students'))[0].n===0,'starter branch creates no fictional students');
const programs=await q('select id,code from public.programs');
await as(owner,second.id);assert((await q('select count(*)::int n from public.programs'))[0].n===4,'second branch has separate starter programmes');
assert(!(await q('select id from public.programs')).some(p=>programs.some(a=>a.id===p.id)),'starter academic IDs are never shared');
await as(outsider,first.id);assert((await q('select count(*)::int n from public.programs'))[0].n===0,'forged branch header cannot read another institution');
await rejects(()=>q('select public.admission_workspace()'),'legacy SECURITY DEFINER workspace denies forged branch');
await as(owner);assert((await q('select count(*)::int n from public.programs'))[0].n===0,'missing selected branch exposes no records');
await as(owner,first.id);
await q('select public.publish_business_rule_version($1,$2,$3::jsonb,$4)',['academics','batch_capacity_policy',JSON.stringify({max_students:15}),'Reviewed demo capacity']);
assert((await q("select payload->>'max_students' max from public.business_rule_versions where status='ACTIVE'"))[0].max==='15','academic capacity changes publish an audited version');
const batch=(await q('select * from public.batches limit 1'))[0];
const payload={request_id:crypto.randomUUID(),student_name:'Test Student',guardian_name:'Test Guardian',mobile:'01712345678',guardian_address:'Central address',consent_to_contact:true,offering_id:batch.offering_id,batch_id:batch.id,reason:'Verified academic intake'};
const intake=(await q('select public.create_staff_admission_intake($1::jsonb) result',[JSON.stringify(payload)]))[0].result;
const command=async(action,id=intake.admission_id)=>(await q('select public.admission_command($1::jsonb) result',[JSON.stringify({request_id:crypto.randomUUID(),action,admission_id:id,reason:'Verified academic placement'})]))[0].result;
await command('READY');
const consentDay=(await q('select current_date::text as consent_day'))[0].consent_day;
await q('select public.record_physical_admission_consent($1::jsonb)',[JSON.stringify({request_id:crypto.randomUUID(),admission_id:intake.admission_id,guardian_signed_on:consentDay,student_signed:false,reason:'Verified signed demo application'})]);
assert(true,'signed academic consent works without a referral or financial prerequisite');
const enrolled=await command('FINALIZE');assert(enrolled.status==='ACTIVE_ENROLLMENT','admission enrolls without fee plan, invoice, payment or payroll');
assert((await q('select count(*)::int n from public.students'))[0].n===1,'enrollment creates one real student identity');
const workspace=(await q('select public.admission_workspace() result'))[0].result;assert(workspace.cases.length===1,'original admission workspace includes finance-free cases');
await as(owner,second.id);assert((await q('select count(*)::int n from public.students'))[0].n===0,'student data remains isolated after branch switch');
await rejects(()=>command('READY'),'admission command cannot act on another branch case');
await as(owner,first.id);await q('select public.add_branch_member($1,$2)',['teacher@example.test','TEACHER']);
await as(teacher,first.id);assert((await q('select public.list_my_branches() result'))[0].result.length===1,'teacher sees only assigned branch');
await rejects(()=>open(crypto.randomUUID(),'Unauthorized','unauthorized-campus'),'branch member cannot open an institution branch');
await as(teacher,second.id);assert((await q("select public.has_permission('academics.view') ok"))[0].ok===false,'teacher cannot select unassigned sibling branch');
await db.exec('reset role');const finance=(await q("select tablename from pg_tables where schemaname='public' and(tablename like 'finance_%' or tablename in('fee_plan_versions','admission_payments','staff_payroll_records'))"));assert(finance.length===0,'financial data tables are absent');
await as(owner,first.id);await rejects(()=>q("select public.finance_command('{}'::jsonb)"),'financial RPC is not executable');
await db.exec('reset role');assert((await q("select count(*)::int n from pg_tables where schemaname='academy'"))[0].n===0,'fresh baseline requires no custom exposed schema');

console.log(`${checks} meaningful database checks passed`);
await as(owner,first.id);
assert((await q('select public.my_erp_context() result'))[0].result.roles.includes('ADMIN'),'selected branch exposes correct ERP context');
for(const [fn,args] of [['academic_workspace',"'2026-01-01'::date,'2026-12-31'::date"],['assessment_workspace',''],['question_bank_workspace',''],['staff_work_workspace',''],['academy_setup_status',''],['admission_directory_options',''],['admin_review_queue','']]){
 const result=(await q(`select public.${fn}(${args}) result`))[0].result;assert(result!==null,`${fn} works without finance setup`);
}
const studentId=(await q('select id from public.students limit 1'))[0].id;
assert((await q('select public.student_profile_workspace($1) result',[studentId]))[0].result.admissions.length===1,'student history includes academic admission with no fee plan');
await q('select public.save_academy_identity($1::jsonb)',[JSON.stringify({name:'Renamed Academy',branch_name:'Renamed Central'})]);
assert((await q('select name from public.branches'))[0].name==='Renamed Central','selected branch identity updates');
await as(owner,second.id);assert((await q('select name from public.branches'))[0].name==='North','sibling branch name remains separate');
await db.exec('reset role');const otherSubject=(await q('select id from public.subjects where scope_branch_id=$1 limit 1',[second.id]))[0].id;
await as(owner,first.id);await db.exec('set role academy_executor');await rejects(()=>q('insert into public.programme_offering_subjects(offering_id,subject_id,sort_order) values($1,$2,99)',[batch.offering_id,otherSubject]),'cross-branch subject link is rejected');
await rejects(()=>q("update public.classes set scope_branch_id=$1",[second.id]),'branch scope cannot be changed');
await as(owner,first.id);await q('select public.add_branch_member($1,$2)',['teacher@example.test','TEACHER']);
const teachSubject=(await q('select id from public.subjects limit 1'))[0].id;
const staff=(await q('select public.create_staff_member($1::jsonb) result',[JSON.stringify({full_name:'Verified Teacher',staff_role_code:'TEACHER',email:'teacher@example.test',mobile:'01912345678',subject_ids:[teachSubject]})]))[0].result;
assert((await q('select profile_id from public.staff where id=$1',[staff.staff_id]))[0].profile_id===teacher,'teacher staff identity links to verified branch member');
const day=(await q('select current_date::text as lesson_day'))[0].lesson_day;
const academic=async(input)=>(await q('select public.academic_command($1::jsonb) result',[JSON.stringify({request_id:crypto.randomUUID(),reason:'Verified teaching setup',...input})]))[0].result;
const room=await academic({action:'CREATE_ROOM',branch_id:first.id,name:'Verified Room',capacity:12});
await academic({action:'CREATE_SESSION',batch_id:batch.id,subject_id:teachSubject,teacher_id:staff.staff_id,room_id:room.id,starts_on:day,start_time:'18:00',end_time:'19:00',planned_scope:'Verified starter lesson'});
assert((await q('select count(*)::int n from public.class_sessions'))[0].n===1,'original teaching workflow creates a branch-scoped session without compensation setup');
await as(teacher,first.id);const session=(await q('select public.academic_workspace($1::date,$1::date) result',[day]))[0].result;assert(session!==null,'teacher can open original academic workspace in assigned branch');
await as(owner,second.id);assert((await q('select count(*)::int n from public.class_sessions'))[0].n===0,'sibling branch cannot read teacher class sessions');
await as(owner,first.id);
await as(owner,second.id);assert((await q('select count(*)::int n from public.staff'))[0].n===0,'teacher staff record stays in its assigned branch');
await as(owner,first.id);
await q('select public.remove_branch_member($1)',['teacher@example.test']);
await as(teacher,first.id);assert((await q("select public.has_permission('academics.view') ok"))[0].ok===false,'removing membership revokes existing session access');
await db.exec('reset role');await q('update public.programme_offerings set is_website_visible=true,is_accepting_applications=true where id=$1',[batch.offering_id]);
await as('', '', 'anon');await q("select set_config('request.headers',$1,false)",[JSON.stringify({'x-academy-public-branch':'central-campus'})]);
const directory=(await q('select public.public_academic_directory() result'))[0].result;assert(directory.classes.length===6,'anonymous directory is limited to selected public branch');
const catalogue=(await q('select public.list_public_programme_offerings() result'))[0].result;assert(catalogue.length===1&&catalogue[0].fee_plan===null,'public catalogue publishes academic programmes without fees');
const publicPayload={student_name:'Public Applicant',guardian_name:'Public Guardian',mobile:'01812345678',class_id:batch.class_id,offering_id:batch.offering_id,program_ids:[batch.program_id],subject_ids:[],consent_to_contact:true,intent:'admission'};
await q('select public.submit_public_interest($1::jsonb)',[JSON.stringify(publicPayload)]);assert(true,'anonymous public application is saved in its branch');
await rejects(()=>q('select public.submit_public_interest($1::jsonb)',[JSON.stringify({...publicPayload,student_name:'Foreign Subject',subject_ids:[otherSubject]})]),'anonymous intake rejects foreign branch academic IDs');
await rejects(()=>q('select * from public.prospects'),'anonymous clients cannot read operational enquiries');
await rejects(()=>q('select * from public.classes'),'anonymous clients cannot bypass the branch directory projection');
await as(owner,second.id);assert((await q('select count(*)::int n from public.prospects'))[0].n===0,'public application cannot leak to sibling branch');

await as(owner);const demo=(await q('select public.open_academy_branch($1,$2,$3,$4,true) result',[crypto.randomUUID(),'Demo Campus','demo-campus',null]))[0].result;
await as(owner,demo.id);
assert((await q('select count(*)::int n from public.students'))[0].n===8,'demo branch seeds eight enrolled students');
assert((await q('select count(*)::int n from public.staff'))[0].n===2,'demo branch seeds two teachers without fake logins');
assert((await q('select count(*)::int n from public.class_sessions'))[0].n===4,'demo branch seeds four lessons');
assert((await q('select count(*)::int n from public.programme_offerings where is_website_visible and is_accepting_applications'))[0].n===4,'demo catalogue is immediately testable');
await as(owner,second.id);assert((await q('select count(*)::int n from public.students'))[0].n===0,'demo student records do not leak to another branch');
console.log(`${checks} meaningful database checks passed`);
await db.close();
