import Link from "next/link";
import { getErpContext } from "@/modules/platform/auth/erp-context";
import { PreferenceControls } from "@/components/shared/preference-controls";
import { cookies } from "next/headers";
import { getMyBranches } from "@/modules/branches/server";
import { openBranch,selectBranch,addBranchMember,removeBranchMember } from "@/modules/branches/actions";
import { LocalizedText } from "@/components/shared/localized-text";
export default async function BranchesPage({searchParams}:{searchParams:Promise<{error?:string;added?:string;removed?:string}>}){
 const branches=await getMyBranches();const selected=(await cookies()).get("academy-branch")?.value;const query=await searchParams;
 const manageUsers=Boolean(selected&&(await getErpContext())?.permissions.includes("system.users.manage"));
 const owner=branches.length===0||branches.some(b=>b.isOwner);
 const input="w-full rounded-xl border bg-background px-3 py-2";const button="rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground";
 return <main className="mx-auto max-w-4xl space-y-7 px-5 py-10"><Link href={selected?"/dashboard":"/"} className="text-primary"><LocalizedText en="← Back" bn="← ফিরে যান"/></Link><PreferenceControls className="w-fit"/><header><h1 className="text-3xl font-bold"><LocalizedText en="Branches" bn="শাখাসমূহ"/></h1><p className="mt-2 text-muted-foreground"><LocalizedText en="Choose your branch. Each branch has its own students, teachers, classes and academic records." bn="আপনার শাখা নির্বাচন করুন। প্রতিটি শাখার শিক্ষার্থী, শিক্ষক, ক্লাস ও শিক্ষার তথ্য পৃথক থাকবে।"/></p></header>
 {query.error&&<p role="alert" className="rounded-xl border border-destructive p-4">{query.error}</p>}{query.added&&<p role="status"><LocalizedText en="Member added to the selected branch." bn="নির্বাচিত শাখায় সদস্য যুক্ত হয়েছে।"/></p>}
 <section className="grid gap-4 sm:grid-cols-2">{branches.map(branch=><form key={branch.id} action={selectBranch} className="space-y-3 rounded-2xl border bg-card p-5"><h2 className="text-xl font-semibold">{branch.name}</h2><p>{branch.organizationName}</p><p className="text-sm text-muted-foreground">{branch.slug}</p><input type="hidden" name="branchId" value={branch.id}/><button className={button}><LocalizedText en={branch.id===selected?"Open current branch":"Select branch"} bn={branch.id===selected?"বর্তমান শাখা খুলুন":"শাখা নির্বাচন করুন"}/></button></form>)}</section>
 {owner&&<form action={openBranch} className="space-y-4 rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold"><LocalizedText en="Open a new branch" bn="নতুন শাখা খুলুন"/></h2><input type="hidden" name="requestId" value={crypto.randomUUID()}/>{branches.length===0&&<label className="block space-y-2"><span><LocalizedText en="Institution name" bn="প্রতিষ্ঠানের নাম"/></span><input className={input} name="organizationName" required minLength={2} maxLength={120}/></label>}{branches.length>0&&<input type="hidden" name="organizationName" value=""/>}<label className="block space-y-2"><span><LocalizedText en="Branch name" bn="শাখার নাম"/></span><input className={input} name="name" required minLength={2} maxLength={120}/></label><label className="block space-y-2"><span><LocalizedText en="Unique branch URL slug" bn="শাখার স্বতন্ত্র URL স্লাগ"/></span><input className={input} name="slug" required pattern="[a-z0-9][a-z0-9-]{2,62}" placeholder="central-campus"/></label><p className="text-sm text-muted-foreground"><LocalizedText en="Starter classes, subjects, Junior Scholarship, SSC, HSC and Job Preparation programmes and 12-seat batches will be added. Review and edit them before publishing. No sample students or teachers are created." bn="প্রাথমিক ক্লাস, বিষয়, জুনিয়র বৃত্তি, এসএসসি, এইচএসসি ও চাকরির প্রস্তুতি প্রোগ্রাম এবং ১২ আসনের ব্যাচ যুক্ত হবে। প্রকাশের আগে পর্যালোচনা করুন। নমুনা শিক্ষার্থী বা শিক্ষক তৈরি হবে না।"/></p><button className={button}><LocalizedText en="Create branch and start" bn="শাখা তৈরি করে শুরু করুন"/></button></form>}
 {manageUsers&&<form action={addBranchMember} className="space-y-4 rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold"><LocalizedText en="Add a verified account to this branch" bn="এই শাখায় যাচাইকৃত অ্যাকাউন্ট যুক্ত করুন"/></h2><label className="block space-y-2"><span>Email</span><input className={input} name="email" type="email" required/></label><label className="block space-y-2"><span><LocalizedText en="Role" bn="ভূমিকা"/></span><select className={input} name="role"><option value="TEACHER">Teacher</option><option value="OPERATOR">Operator</option><option value="ACADEMIC_DIRECTOR">Academic Director</option><option value="ADMIN">Branch Admin</option></select></label><button className={button}><LocalizedText en="Add member" bn="সদস্য যুক্ত করুন"/></button></form>}
 {manageUsers&&<form action={removeBranchMember} className="space-y-4 rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold"><LocalizedText en="Remove branch access" bn="শাখার প্রবেশাধিকার সরান"/></h2><label className="block space-y-2"><span>Email</span><input className={input} name="email" type="email" required/></label><button className="rounded-xl border px-5 py-3 font-semibold"><LocalizedText en="Remove member from this branch" bn="এই শাখা থেকে সদস্য সরান"/></button>{query.removed&&<p role="status"><LocalizedText en="Branch access removed." bn="শাখার প্রবেশাধিকার সরানো হয়েছে।"/></p>}</form>}
 </main>;
}
