import {PhysicalConsentForm} from "@/modules/admissions/components/physical-consent-form";
import {AdmissionIdentityEditor} from "@/modules/admissions/components/identity-editor";
import Link from "next/link";
import {notFound} from "next/navigation";
import {PageHeader} from "@/components/erp/page-header";
import {StatusBadge} from "@/components/erp/status-badge";
import {requirePermission} from "@/modules/platform/auth/erp-context";
import {getAdmissionCase,getAdmissionWorkspace} from "@/modules/admissions/queries";
import {AdmissionCommandForm} from "@/modules/admissions/components/command-form";
export default async function AdmissionCasePage({params}:{params:Promise<{admissionId:string}>}){
 const context=await requirePermission("admissions.view");const{admissionId}=await params;const data=await getAdmissionWorkspace();const item=data.cases.find(c=>c.id===admissionId);if(!item)notFound();const batch=data.batches.find(b=>b.id===item.batchId);const detail=await getAdmissionCase(item.id);const canManage=context.permissions.includes("admissions.create");
 return <div className="space-y-7"><PageHeader eyebrow="Admissions" title={`${item.number} · ${item.name}`} description="Verify the applicant, review the academic placement, then enroll. Each change remains in this branch’s audit history."/><Link href="/dashboard/admissions" className="underline">← Admission register</Link><section className="space-y-4 rounded-2xl border bg-card p-6"><StatusBadge value={item.status}/><dl className="grid gap-4 sm:grid-cols-2">{[["Student",item.name],["Guardian",item.guardian],["Mobile",item.mobile],["Programme",batch?.offeringName],["Batch",batch?.name],["Branch",batch?.branchName],["Student number",item.studentNo]].map(([label,value])=><div key={label}><dt className="text-sm text-muted-foreground">{label}</dt><dd className="font-semibold">{value??"—"}</dd></div>)}</dl></section><Link href={`/dashboard/admissions/${item.id}/print`} className="inline-flex rounded-xl border p-3">Print application →</Link>{canManage&&!item.existingStudent&&["DRAFT","READY"].includes(item.status)&&<AdmissionIdentityEditor admission={detail}/>} {canManage&&["DRAFT","READY"].includes(item.status)&&<details className="rounded-2xl border bg-card p-5"><summary className="cursor-pointer font-semibold">Record signed application evidence</summary><PhysicalConsentForm admissionId={item.id}/></details>} {canManage&&item.status==="DRAFT"&&<AdmissionCommandForm action="READY" admissionId={item.id} data={data} label="Verify and mark ready" description="Confirm the student and guardian details and selected programme."/>}{canManage&&item.status==="READY"&&<AdmissionCommandForm action="ACCEPT" admissionId={item.id} data={data} label="Confirm academic enrollment" description="Create the student identity and enroll in the selected batch. Capacity is checked again before saving."/>}{item.studentId&&<Link href={`/dashboard/students/${item.studentId}`} className="inline-flex rounded-xl border p-4 font-semibold">Open student record →</Link>}</div>;
}
