"use client";
import {useState,useTransition,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {LocalizedText} from "@/components/shared/localized-text";
import {createBranchStaff} from "../create-actions";
export function CreateStaffForm({roles,subjects}:{roles:{code:string;name:string}[];subjects:{id:string;name:string}[]}){
 const[pending,start]=useTransition();const[message,setMessage]=useState("");const router=useRouter();const control="mt-1 w-full rounded-xl border bg-background p-3";
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);start(async()=>{try{const result=await createBranchStaff({...Object.fromEntries(data),subject_ids:data.getAll("subject_ids")});setMessage(result.message);if(result.ok){form.reset();router.refresh();}}catch{setMessage("Could not confirm the save. Refresh before retrying.");}});}
 return <details className="rounded-2xl border bg-card p-5"><summary className="cursor-pointer font-semibold"><LocalizedText en="Create staff identity" bn="স্টাফ পরিচয় তৈরি করুন"/></summary><p className="mt-3 text-sm text-muted-foreground"><LocalizedText en="For account access, first add the verified email under Branches. This record describes the person’s work in the selected branch." bn="অ্যাকাউন্টের প্রবেশাধিকারের জন্য প্রথমে শাখাসমূহ থেকে যাচাইকৃত ইমেইল যুক্ত করুন। এই রেকর্ড নির্বাচিত শাখায় ব্যক্তির কাজের পরিচয় রাখবে।"/></p><form onSubmit={submit} className="mt-4 grid gap-4 sm:grid-cols-2"><label><LocalizedText en="Full name" bn="পূর্ণ নাম"/><input name="full_name" className={control} required minLength={2} maxLength={160}/></label><label><LocalizedText en="Mobile" bn="মোবাইল"/><input name="mobile" className={control} required pattern="01[3-9][0-9]{8}"/></label><label>Email<input name="email" className={control} type="email"/></label><label><LocalizedText en="Staff role" bn="স্টাফের ভূমিকা"/><select name="staff_role_code" className={control} required><option value="">Choose role</option>{roles.map(role=><option key={role.code} value={role.code}>{role.name}</option>)}</select></label><fieldset className="sm:col-span-2"><legend><LocalizedText en="Teaching subjects (teaching roles only)" bn="পাঠদানের বিষয় (শুধু শিক্ষকতার ভূমিকা)"/></legend><div className="mt-2 flex flex-wrap gap-4">{subjects.map(subject=><label key={subject.id} className="flex items-center gap-2"><input type="checkbox" name="subject_ids" value={subject.id}/>{subject.name}</label>)}</div></fieldset>{message&&<p role="status" className="sm:col-span-2">{message}</p>}<button disabled={pending} className="rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground"><LocalizedText en={pending?"Saving…":"Create staff"} bn={pending?"সংরক্ষণ হচ্ছে…":"স্টাফ তৈরি করুন"}/></button></form></details>;
}
