"use client";
import {useState,useTransition,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {useLanguage} from "@/components/providers/language-provider";
export function BranchAccountForm(){
 const{locale}=useLanguage();const t=(en:string,bn:string)=>locale==="bn"?bn:en;const[message,setMessage]=useState("");const[pending,start]=useTransition();const router=useRouter();const control="mt-1 min-h-11 w-full rounded-xl border bg-background px-3";
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);start(async()=>{try{const{data,error}=await createClient().auth.signUp({email:String(form.get("email")),password:String(form.get("password")),options:{data:{full_name:String(form.get("full_name"))},emailRedirectTo:new URL("/auth/confirm?next=/branches",window.location.origin).toString()}});if(error){setMessage(error.message);return;}if(data.session){router.push("/branches");router.refresh();return;}setMessage(t("Check your email and verify your account. Then sign in to open a branch or ask your branch administrator to add you.","ইমেইল দেখে অ্যাকাউন্ট যাচাই করুন। এরপর প্রবেশ করে শাখা খুলুন অথবা আপনার শাখার প্রশাসককে আপনাকে যুক্ত করতে বলুন।"));}catch{setMessage(t("Could not create the account. Try again.","অ্যাকাউন্ট তৈরি করা যায়নি। আবার চেষ্টা করুন।"));}});}
 return <form onSubmit={submit} className="space-y-5"><label className="block text-sm">{t("Full name","পূর্ণ নাম")}<input name="full_name" required minLength={2} maxLength={160} autoComplete="name" className={control}/></label><label className="block text-sm">{t("Email","ইমেইল")}<input name="email" type="email" required autoComplete="email" className={control}/></label><label className="block text-sm">{t("Password","পাসওয়ার্ড")}<input name="password" type="password" required minLength={8} autoComplete="new-password" className={control}/></label>{message&&<p role="status" className="rounded-xl border p-4">{message}</p>}<button disabled={pending} className="min-h-11 w-full rounded-xl bg-primary font-semibold text-primary-foreground">{pending?t("Creating account…","অ্যাকাউন্ট তৈরি হচ্ছে…"):t("Create account","অ্যাকাউন্ট তৈরি করুন")}</button></form>;
}
