// Original Sohoj Academy bilingual copy; editable without changing page structure.
// Keys are persistent configuration identifiers: append new entries; never renumber.
export const siteCopy = [
  {
    key: "text_0",
    group: "Home",
    en: "Small learning groups",
    bn: "ছোট শেখার দল",
  },
  {
    key: "text_1",
    group: "Home",
    en: "Small batches make personal attention practical, not promotional.",
    bn: "ছোট ব্যাচে ব্যক্তিগত মনোযোগ বাস্তবে দেওয়া সম্ভব হয়।",
  },
  {
    key: "text_2",
    group: "Home",
    en: "Continuous assessment",
    bn: "ধারাবাহিক মূল্যায়ন",
  },
  {
    key: "text_3",
    group: "Home",
    en: "Regular practice and review help make progress measurable.",
    bn: "নিয়মিত অনুশীলন ও পর্যালোচনা অগ্রগতি পরিমাপে সাহায্য করে।",
  },
  {
    key: "text_4",
    group: "Home",
    en: "Guardian visibility",
    bn: "অভিভাবকের স্পষ্ট ধারণা",
  },
  {
    key: "text_5",
    group: "Home",
    en: "Attendance, results and progress records support clearer guardian follow-up.",
    bn: "উপস্থিতি, ফলাফল ও অগ্রগতির রেকর্ড অভিভাবকের নিয়মিত অনুসরণকে সহজ করে।",
  },
  {
    key: "text_6",
    group: "Home",
    en: "Structured academic records",
    bn: "গোছানো একাডেমিক রেকর্ড",
  },
  {
    key: "text_7",
    group: "Home",
    en: "Learning history is organised so important progress does not disappear between classes.",
    bn: "শেখার ইতিহাস সংগঠিত থাকে, যাতে ক্লাসের মাঝে গুরুত্বপূর্ণ অগ্রগতি হারিয়ে না যায়।",
  },
  {
    key: "text_8",
    group: "Home",
    en: "Understand",
    bn: "বুঝি",
  },
  {
    key: "text_9",
    group: "Home",
    en: "Concept first",
    bn: "আগে ধারণা পরিষ্কার করি",
  },
  {
    key: "text_10",
    group: "Home",
    en: "Practise",
    bn: "অনুশীলন করি",
  },
  {
    key: "text_11",
    group: "Home",
    en: "Practise deliberately",
    bn: "উদ্দেশ্যপূর্ণ অনুশীলন করি",
  },
  {
    key: "text_12",
    group: "Home",
    en: "Assess",
    bn: "পরীক্ষা দিই",
  },
  {
    key: "text_13",
    group: "Home",
    en: "Measure learning",
    bn: "শেখা কতটুকু হয়েছে যাচাই করি",
  },
  {
    key: "text_14",
    group: "Home",
    en: "Analyse",
    bn: "বিশ্লেষণ করি",
  },
  {
    key: "text_15",
    group: "Home",
    en: "Find the gap",
    bn: "ঘাটতি চিহ্নিত করি",
  },
  {
    key: "text_16",
    group: "Home",
    en: "Small batch • Personal attention • Visible progress",
    bn: "ছোট ব্যাচ • ব্যক্তিগত মনোযোগ • দৃশ্যমান অগ্রগতি",
  },
  {
    key: "text_17",
    group: "Home",
    en: "Learning should be",
    bn: "শিক্ষা হোক",
  },
  {
    key: "text_18",
    group: "Home",
    en: "easy and enjoyable",
    bn: "সহজ ও আনন্দময়",
  },
  {
    key: "text_19",
    group: "Home",
    en: "Sohoj Academy is built around focused teaching, regular practice and measurable progress—so students know what to improve and guardians can follow the learning journey with confidence.",
    bn: "সহজ একাডেমিতে মনোযোগী পাঠদান, নিয়মিত অনুশীলন এবং পরিমাপযোগ্য অগ্রগতির ওপর গুরুত্ব দেওয়া হয়—যাতে শিক্ষার্থী বুঝতে পারে কোথায় উন্নতি প্রয়োজন এবং অভিভাবক আত্মবিশ্বাসের সঙ্গে শেখার যাত্রা অনুসরণ করতে পারেন।",
  },
  {
    key: "text_20",
    group: "Home",
    en: "Register Interest",
    bn: "আগ্রহ নিবন্ধন করুন",
  },
  {
    key: "text_21",
    group: "Home",
    en: "Explore Programs",
    bn: "প্রোগ্রাম দেখুন",
  },
  {
    key: "text_22",
    group: "Home",
    en: "Class 8–12 focus",
    bn: "ক্লাস ৮–১২ ফোকাস",
  },
  {
    key: "text_23",
    group: "Home",
    en: "12 students per batch",
    bn: "প্রতি ব্যাচে ১২ জন",
  },
  {
    key: "text_24",
    group: "Home",
    en: "Regular progress review",
    bn: "নিয়মিত অগ্রগতি পর্যালোচনা",
  },
  {
    key: "text_25",
    group: "Home",
    en: "LEARNING, MADE CLEAR",
    bn: "সহজভাবে শেখা",
  },
  {
    key: "text_26",
    group: "Home",
    en: "A classroom where every question gets room.",
    bn: "যে শ্রেণিকক্ষে প্রতিটি প্রশ্নের জন্য জায়গা আছে।",
  },
  {
    key: "text_27",
    group: "Home",
    en: "The Sohoj Learning Method",
    bn: "সহজ একাডেমির শেখার পদ্ধতি",
  },
  {
    key: "text_28",
    group: "Home",
    en: "A clear path from first understanding to steady improvement.",
    bn: "প্রথম ধারণা থেকে ধারাবাহিক উন্নতি—একটি পরিষ্কার শেখার পথ।",
  },
  {
    key: "text_29",
    group: "Home",
    en: "When a test reveals a gap, students return to the concept and practise again. Learning moves forward when understanding is stronger.",
    bn: "পরীক্ষায় ঘাটতি ধরা পড়লে শিক্ষার্থী ধারণায় ফিরে গিয়ে আবার অনুশীলন করে। বোঝাপড়া শক্ত হলে শেখা সামনে এগোয়।",
  },
  {
    key: "text_30",
    group: "Home",
    en: "Understand → Practise → Improve",
    bn: "বুঝি → অনুশীলন → উন্নতি",
  },
  {
    key: "text_31",
    group: "Home",
    en: "Every gap becomes the next practice target.",
    bn: "প্রতিটি ঘাটতিই পরবর্তী অনুশীলনের লক্ষ্য।",
  },
  {
    key: "text_32",
    group: "Home",
    en: "Sohoj Learning Method",
    bn: "সহজ লার্নিং মেথড",
  },
  {
    key: "text_33",
    group: "Home",
    en: "Learn → practise → measure → improve",
    bn: "বুঝি → অনুশীলন করি → পরীক্ষা দিই → উন্নতি করি",
  },
  {
    key: "text_34",
    group: "Home",
    en: "80% mastery achieved?",
    bn: "৮০% দক্ষতা অর্জিত?",
  },
  {
    key: "text_35",
    group: "Home",
    en: "YES → Move forward",
    bn: "হ্যাঁ → এগিয়ে যাই",
  },
  {
    key: "text_36",
    group: "Home",
    en: "If not, return to practice, fix the gap and measure again.",
    bn: "না হলে অনুশীলনে ফিরে গিয়ে ঘাটতি ঠিক করি—তারপর আবার যাচাই করি।",
  },
  {
    key: "text_37",
    group: "Home",
    en: "Example progress snapshot",
    bn: "উদাহরণ অগ্রগতি চিত্র",
  },
  {
    key: "text_38",
    group: "Home",
    en: "Weekly learning review",
    bn: "সাপ্তাহিক শেখার পর্যালোচনা",
  },
  {
    key: "text_39",
    group: "Home",
    en: "Why Sohoj",
    bn: "কেন সহজ একাডেমি",
  },
  {
    key: "text_40",
    group: "Home",
    en: "Attention you can see in the learning.",
    bn: "শেখার অগ্রগতিতে স্পষ্ট মনোযোগ।",
  },
  {
    key: "text_41",
    group: "Home",
    en: "Find the right next step for your student.",
    bn: "আপনার শিক্ষার্থীর জন্য সঠিক পরবর্তী পদক্ষেপটি খুঁজুন।",
  },
  {
    key: "text_42",
    group: "Home",
    en: "View Programs",
    bn: "প্রোগ্রাম দেখুন",
  },
  {
    key: "text_43",
    group: "Home",
    en: "© Sohoj Academy. Academic support and Digital Campus.",
    bn: "© সহজ একাডেমি। একাডেমিক সহায়তা ও ডিজিটাল ক্যাম্পাস।",
  },
  {
    key: "text_44",
    group: "Home",
    en: "About",
    bn: "পরিচিতি",
  },
  {
    key: "text_45",
    group: "Home",
    en: "FAQ",
    bn: "প্রশ্নোত্তর",
  },
  {
    key: "text_46",
    group: "Home",
    en: "Journal",
    bn: "শিক্ষা-জার্নাল",
  },
  {
    key: "text_47",
    group: "about",
    en: "Teach for understanding",
    bn: "বোঝার জন্য শেখানো",
  },
  {
    key: "text_48",
    group: "about",
    en: "Start with clear concepts, then give students time to practise and ask questions.",
    bn: "ধারণা পরিষ্কার করে শুরু করি, তারপর অনুশীলন ও প্রশ্নের জন্য সময় রাখি।",
  },
  {
    key: "text_49",
    group: "about",
    en: "Notice what needs work",
    bn: "কোথায় উন্নতি দরকার খেয়াল রাখা",
  },
  {
    key: "text_50",
    group: "about",
    en: "Use regular exercises and assessments to find learning gaps and plan the next lesson.",
    bn: "নিয়মিত অনুশীলন ও মূল্যায়নের মাধ্যমে শেখার ঘাটতি বুঝে পরের পাঠ সাজাই।",
  },
  {
    key: "text_51",
    group: "about",
    en: "Keep guardians informed",
    bn: "অভিভাবককে অবহিত রাখা",
  },
  {
    key: "text_52",
    group: "about",
    en: "Make attendance, learning progress and next steps easier for families to follow.",
    bn: "উপস্থিতি, শেখার অগ্রগতি ও পরবর্তী পদক্ষেপ পরিবার যেন সহজে অনুসরণ করতে পারে।",
  },
  {
    key: "text_53",
    group: "about",
    en: "About Sohoj Academy",
    bn: "সহজ একাডেমি সম্পর্কে",
  },
  {
    key: "text_54",
    group: "about",
    en: "A focused place to learn with confidence.",
    bn: "আত্মবিশ্বাস নিয়ে শেখার একটি মনোযোগী পরিবেশ।",
  },
  {
    key: "text_55",
    group: "about",
    en: "Sohoj Academy supports students in Classes 8–12 with clear teaching, purposeful practice and a steady view of progress.",
    bn: "সহজ একাডেমি ৮–১২ম শ্রেণির শিক্ষার্থীদের স্পষ্ট পাঠদান, উদ্দেশ্যপূর্ণ অনুশীলন এবং অগ্রগতির নিয়মিত ধারণা দিয়ে সহায়তা করে।",
  },
  {
    key: "text_56",
    group: "about",
    en: "Making difficult things easier to learn.",
    bn: "কঠিন বিষয় সহজ করে শেখা।",
  },
  {
    key: "text_57",
    group: "about",
    en: "Our purpose",
    bn: "আমাদের লক্ষ্য",
  },
  {
    key: "text_58",
    group: "about",
    en: "Mission",
    bn: "মিশন",
  },
  {
    key: "text_59",
    group: "about",
    en: "Make learning clear, engaging and manageable by helping students understand concepts, practise with purpose and see what to work on next.",
    bn: "শিক্ষার্থী যেন ধারণা বুঝতে পারে, উদ্দেশ্য নিয়ে অনুশীলন করে এবং পরবর্তী করণীয় জানতে পারে—এভাবে শেখাকে স্পষ্ট, আনন্দদায়ক ও সহজসাধ্য করা।",
  },
  {
    key: "text_60",
    group: "about",
    en: "Vision",
    bn: "ভিশন",
  },
  {
    key: "text_61",
    group: "about",
    en: "Build a trusted local learning community where every student receives attention, useful feedback and a clear path to improve.",
    bn: "এমন একটি বিশ্বস্ত স্থানীয় শেখার পরিবেশ গড়ে তোলা, যেখানে প্রতিটি শিক্ষার্থী মনোযোগ, কার্যকর মতামত এবং উন্নতির পরিষ্কার পথ পায়।",
  },
  {
    key: "text_62",
    group: "about",
    en: "What families can expect",
    bn: "পরিবার যা আশা করতে পারে",
  },
  {
    key: "text_63",
    group: "about",
    en: "A thoughtful routine, from lesson to feedback.",
    bn: "পাঠ থেকে মতামত—একটি যত্নশীল ধারাবাহিকতা।",
  },
  {
    key: "text_64",
    group: "about",
    en: "Explore current programmes",
    bn: "বর্তমান প্রোগ্রাম দেখুন",
  },
  {
    key: "text_65",
    group: "faq",
    en: "Which students does Sohoj Academy support?",
    bn: "সহজ একাডেমি কোন শিক্ষার্থীদের সহায়তা করে?",
  },
  {
    key: "text_66",
    group: "faq",
    en: "Sohoj Academy focuses on academic support for Classes 8–10. The current programme offerings show the classes and subjects available for registration.",
    bn: "সহজ একাডেমি ৮–১০ম শ্রেণির একাডেমিক সহায়তায় গুরুত্ব দেয়। বর্তমানে কোন শ্রেণি ও বিষয়ের জন্য নিবন্ধন চলছে তা প্রোগ্রাম কার্ডে দেখা যাবে।",
  },
  {
    key: "text_67",
    group: "faq",
    en: "Does registering interest confirm admission?",
    bn: "আগ্রহ নিবন্ধন করলেই কি ভর্তি নিশ্চিত হয়?",
  },
  {
    key: "text_68",
    group: "faq",
    en: "No. Interest registration helps the academy understand what support is needed. Staff follow up and verify details; admission is confirmed only after the admission process is completed.",
    bn: "না। আগ্রহ নিবন্ধন একাডেমিকে প্রয়োজন বুঝতে সাহায্য করে। স্টাফ তথ্য যাচাই করে যোগাযোগ করবেন; ভর্তি প্রক্রিয়া সম্পন্ন হওয়ার পরই ভর্তি নিশ্চিত হয়।",
  },
  {
    key: "text_69",
    group: "faq",
    en: "How do I apply for an open programme?",
    bn: "উন্মুক্ত প্রোগ্রামে কীভাবে আবেদন করব?",
  },
  {
    key: "text_70",
    group: "faq",
    en: "Choose an offering marked as accepting applications and use its admission application button. The form can be submitted without creating a student account.",
    bn: "আবেদন গ্রহণ করছে এমন প্রোগ্রাম বেছে নিয়ে তার ভর্তি আবেদন বাটনে চাপ দিন। শিক্ষার্থী অ্যাকাউন্ট তৈরি না করেই ফর্ম জমা দেওয়া যায়।",
  },
  {
    key: "text_71",
    group: "faq",
    en: "Where can I find programme fees and subjects?",
    bn: "প্রোগ্রামের ফি ও বিষয় কোথায় পাব?",
  },
  {
    key: "text_72",
    group: "faq",
    en: "Each programme card shows its published fee summary, subjects and application status. Open the programme details for schedule, requirements and other information when available.",
    bn: "প্রতিটি প্রোগ্রাম কার্ডে প্রকাশিত ফি, বিষয় এবং আবেদন অবস্থা দেখানো হয়। সময়সূচি, শর্ত ও অন্যান্য তথ্য থাকলে বিস্তারিত অংশ খুলে দেখুন।",
  },
  {
    key: "text_73",
    group: "faq",
    en: "How are batch and class placement confirmed?",
    bn: "ব্যাচ ও শ্রেণি নির্ধারণ কীভাবে নিশ্চিত হয়?",
  },
  {
    key: "text_74",
    group: "faq",
    en: "The academy checks the student's application and available placement options. Submitting an interest or application form does not reserve a seat by itself.",
    bn: "একাডেমি শিক্ষার্থীর আবেদন এবং উপলভ্য স্থান যাচাই করে। আগ্রহ বা আবেদন ফর্ম জমা দিলেই আসন সংরক্ষিত হয় না।",
  },
  {
    key: "text_75",
    group: "faq",
    en: "Can a guardian submit the form for a student?",
    bn: "অভিভাবক কি শিক্ষার্থীর হয়ে ফর্ম জমা দিতে পারেন?",
  },
  {
    key: "text_76",
    group: "faq",
    en: "Yes. A parent or guardian can provide the student's details and their own contact information so the academy can follow up.",
    bn: "হ্যাঁ। অভিভাবক শিক্ষার্থীর তথ্য ও নিজের যোগাযোগের তথ্য দিয়ে একাডেমির ফলো-আপের জন্য ফর্ম জমা দিতে পারেন।",
  },
  {
    key: "text_77",
    group: "faq",
    en: "Help for families",
    bn: "পরিবারের জন্য সহায়তা",
  },
  {
    key: "text_78",
    group: "faq",
    en: "Questions, answered clearly.",
    bn: "আপনার প্রশ্নের সহজ উত্তর।",
  },
  {
    key: "text_79",
    group: "faq",
    en: "A few practical details about programmes, registration and what happens after a form is submitted.",
    bn: "প্রোগ্রাম, নিবন্ধন এবং ফর্ম জমা দেওয়ার পর কী হয়—কিছু প্রয়োজনীয় তথ্য এখানে দেওয়া হলো।",
  },
  {
    key: "text_80",
    group: "faq",
    en: "Ready to see which programmes are open?",
    bn: "কোন প্রোগ্রামে আবেদন চলছে দেখতে চান?",
  },
  {
    key: "text_81",
    group: "faq",
    en: "Browse programmes",
    bn: "প্রোগ্রাম দেখুন",
  },
  {
    key: "text_82",
    group: "journal",
    en: "STUDY HABITS",
    bn: "পড়াশোনার অভ্যাস",
  },
  {
    key: "text_83",
    group: "journal",
    en: "A study session that has a clear finish line",
    bn: "যে পড়ার সেশনের শেষ লক্ষ্য পরিষ্কার",
  },
  {
    key: "text_84",
    group: "journal",
    en: "Replace an open-ended ‘study more’ goal with one small outcome a student can check.",
    bn: "‘আরও পড়ব’—এমন অস্পষ্ট লক্ষ্য না রেখে শিক্ষার্থী যাচাই করতে পারে এমন ছোট লক্ষ্য ঠিক করুন।",
  },
  {
    key: "text_85",
    group: "journal",
    en: "Choose one topic and define what ‘done’ means: explain the idea without notes, solve a short set of questions, or correct yesterday’s mistakes. Keep the session focused on that outcome.",
    bn: "একটি বিষয় বেছে নিয়ে ‘শেষ’ বলতে কী বোঝায় ঠিক করুন: নোট ছাড়া ধারণাটি বোঝানো, কয়েকটি প্রশ্ন সমাধান, অথবা গতকালের ভুল সংশোধন। পুরো সেশনটি সেই লক্ষ্যেই রাখুন।",
  },
  {
    key: "text_86",
    group: "journal",
    en: "At the end, ask the student to mark what felt easy and what still needs help. That note becomes the starting point for the next session.",
    bn: "শেষে শিক্ষার্থীকে বলতে বলুন কোন অংশ সহজ লেগেছে এবং কোথায় আরও সাহায্য দরকার। পরের সেশনের শুরু হবে সেই নোট থেকে।",
  },
  {
    key: "text_87",
    group: "journal",
    en: "TEST REVIEW",
    bn: "পরীক্ষা পর্যালোচনা",
  },
  {
    key: "text_88",
    group: "journal",
    en: "Use mistakes as a map for the next lesson",
    bn: "ভুলকে পরের পাঠের দিকনির্দেশনা করুন",
  },
  {
    key: "text_89",
    group: "journal",
    en: "A test result is more useful when students can see why an answer went wrong and what to practise next.",
    bn: "কেন উত্তর ভুল হয়েছে এবং এরপর কী অনুশীলন করতে হবে বুঝলে পরীক্ষার ফল বেশি কাজে লাগে।",
  },
  {
    key: "text_90",
    group: "journal",
    en: "After a quiz, sort mistakes into a few simple groups: the idea was unclear, a step was skipped, the question was misread, or the answer was not checked. Avoid correcting only the final number.",
    bn: "কুইজের পর ভুলগুলো কয়েকটি সহজ ভাগে রাখুন: ধারণা অস্পষ্ট ছিল, ধাপ বাদ গেছে, প্রশ্ন ভুল পড়া হয়েছে, অথবা উত্তর যাচাই করা হয়নি। শুধু শেষের সংখ্যাটি ঠিক করে থেমে যাবেন না।",
  },
  {
    key: "text_91",
    group: "journal",
    en: "Pick one recurring pattern and practise it with a fresh example. Then revisit it in a later session to see whether the correction stuck.",
    bn: "বারবার হওয়া একটি ভুল বেছে নতুন উদাহরণে অনুশীলন করুন। পরে আবার সেটি দেখে সংশোধনটি স্থায়ী হয়েছে কি না যাচাই করুন।",
  },
  {
    key: "text_92",
    group: "journal",
    en: "FOR GUARDIANS",
    bn: "অভিভাবকদের জন্য",
  },
  {
    key: "text_93",
    group: "journal",
    en: "Support a learner without taking over",
    bn: "শিক্ষার্থীর হয়ে না করে পাশে থাকুন",
  },
  {
    key: "text_94",
    group: "journal",
    en: "A calm check-in can help a student plan, reflect and ask for support while keeping ownership of the work.",
    bn: "শান্তভাবে খোঁজ নিলে শিক্ষার্থী পরিকল্পনা করতে, ভাবতে এবং সাহায্য চাইতে পারে—কাজের দায়িত্ব নিজের কাছেই থাকে।",
  },
  {
    key: "text_95",
    group: "journal",
    en: "Ask what the student is working on, what feels difficult and what the next small step could be. Give them time to answer before suggesting a solution.",
    bn: "শিক্ষার্থীকে জিজ্ঞেস করুন সে কী পড়ছে, কোন অংশ কঠিন লাগছে এবং পরের ছোট পদক্ষেপ কী হতে পারে। সমাধান বলার আগে তাকে উত্তর দেওয়ার সময় দিন।",
  },
  {
    key: "text_96",
    group: "journal",
    en: "Notice steady effort and specific progress, not only marks. If a difficulty continues, share the observation with the teacher so support can be planned together.",
    bn: "শুধু নম্বর নয়, ধারাবাহিক চেষ্টা ও নির্দিষ্ট অগ্রগতিও খেয়াল করুন। কোনো সমস্যা চলতে থাকলে শিক্ষককে জানান, যাতে একসঙ্গে সহায়তার পরিকল্পনা করা যায়।",
  },
  {
    key: "text_97",
    group: "journal",
    en: "Sohoj Learning Journal",
    bn: "সহজ একাডেমি শিক্ষা-জার্নাল",
  },
  {
    key: "text_98",
    group: "journal",
    en: "Small ideas for better learning.",
    bn: "আরও ভালো শেখার জন্য ছোট কিছু ভাবনা।",
  },
  {
    key: "text_99",
    group: "journal",
    en: "Practical notes for students and guardians on study habits, test review and everyday learning.",
    bn: "পড়ার অভ্যাস, পরীক্ষা পর্যালোচনা এবং প্রতিদিনের শেখা নিয়ে শিক্ষার্থী ও অভিভাবকদের জন্য ব্যবহারিক লেখা।",
  },
  {
    key: "text_100",
    group: "journal",
    en: "Read article",
    bn: "লেখাটি পড়ুন",
  },
  {
    key: "text_101",
    group: "journal",
    en: "Close article",
    bn: "লেখা বন্ধ করুন",
  },
  {
    key: "text_102",
    group: "Registration",
    en: "Go to homepage",
    bn: "মূল পাতায় ফিরুন",
  },
  {
    key: "text_103",
    group: "Registration",
    en: "Admission application",
    bn: "ভর্তির আবেদন",
  },
  {
    key: "text_104",
    group: "Registration",
    en: "Student Interest Registration",
    bn: "শিক্ষার্থী আগ্রহ নিবন্ধন",
  },
  {
    key: "text_105",
    group: "Registration",
    en: "Apply for an open programme offering.",
    bn: "উন্মুক্ত প্রোগ্রাম অফারিংয়ে ভর্তির আবেদন করুন।",
  },
  {
    key: "text_106",
    group: "Registration",
    en: "Tell us what support the student is looking for.",
    bn: "শিক্ষার্থী কী ধরনের সহায়তা খুঁজছে তা আমাদের জানান।",
  },
  {
    key: "text_107",
    group: "Registration",
    en: "Choose an offering that is currently accepting applications. Staff will verify the details before any admission is confirmed.",
    bn: "বর্তমানে আবেদন গ্রহণ করছে এমন একটি অফারিং বেছে নিন। ভর্তি নিশ্চিত হওয়ার আগে স্টাফ তথ্য যাচাই করবে।",
  },
  {
    key: "text_108",
    group: "Registration",
    en: "This short registration helps Sohoj Academy understand the student's class, programme or subject interests and preferred schedule before admission.",
    bn: "এই সংক্ষিপ্ত নিবন্ধন ভর্তির আগে শিক্ষার্থীর ক্লাস, প্রোগ্রাম বা বিষয় আগ্রহ এবং পছন্দের সময় বুঝতে সাহায্য করে।",
  },
  {
    key: "text_109",
    group: "Registration",
    en: "This is not admission",
    bn: "এটি ভর্তি নয়",
  },
  {
    key: "text_110",
    group: "Registration",
    en: "No fee or permanent Student ID is created by this form until staff complete verification and admission.",
    bn: "স্টাফ যাচাই ও ভর্তি সম্পন্ন না করা পর্যন্ত এই ফর্ম থেকে ফি বা স্থায়ী Student ID তৈরি হয় না।",
  },
  {
    key: "text_111",
    group: "Registration",
    en: "Structured follow-up",
    bn: "গোছানো ফলো-আপ",
  },
  {
    key: "text_112",
    group: "Registration",
    en: "The information becomes a traceable prospect record for academy follow-up.",
    bn: "তথ্যগুলো একাডেমির ফলো-আপের জন্য ট্রেসযোগ্য Prospect রেকর্ড হিসেবে সংরক্ষিত হয়।",
  },
  {
    key: "text_113",
    group: "Registration",
    en: "Applications are closed for the programme you selected. Choose another open offering below, or register general interest.",
    bn: "আপনি যে প্রোগ্রামটি বেছেছিলেন তার আবেদন বর্তমানে বন্ধ। নিচে অন্য উন্মুক্ত অফারিং বেছে নিন, অথবা সাধারণ আগ্রহ নিবন্ধন করুন।",
  },
  {
    key: "text_114",
    group: "Registration",
    en: "The registration choices are temporarily unavailable. Please refresh after the academy database update is completed.",
    bn: "নিবন্ধনের অপশনগুলো সাময়িকভাবে পাওয়া যাচ্ছে না। একাডেমির ডাটাবেজ আপডেট সম্পন্ন হলে পেজটি রিফ্রেশ করুন।",
  },
  {
    key: "text_115",
    group: "Registration",
    en: "Learning should be easy and enjoyable",
    bn: "শিক্ষা হোক সহজ ও আনন্দময়",
  },
] as const;
