// Generate public schema types from the tested final model, not from historical SQL.
import {db} from '../simplified/database.mjs';
import {writeFile} from 'node:fs/promises';
const q=async(s)=>(await db.query(s)).rows;
const enums=await q("select t.typname,array_agg(e.enumlabel order by e.enumsortorder) labels from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum e on e.enumtypid=t.oid where n.nspname='public' group by t.typname order by t.typname");
const enumNames=new Set(enums.map(e=>e.typname));
function type(t){if(t.endsWith('[]'))return '('+type(t.slice(0,-2))+')[]';t=t.replace(/^public\./,'');if(enumNames.has(t))return 'Database["public"]["Enums"]["'+t+'"]';if(/^(smallint|integer|bigint|numeric|real|double precision)/.test(t))return 'number';if(t==='boolean')return 'boolean';if(t==='jsonb'||t==='json')return 'Json';if(t==='void')return 'undefined';if(t==='record')return 'Record<string, Json>';return 'string';}
let out='// Generated from the reviewed academic schema. Regenerate with node scripts/database/generate-types.mjs.\nexport type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\nexport type Database = { public: { Tables: {\n';
const tables=await q("select c.oid,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' order by c.relname");
for(const t of tables){const cols=await q(`select a.attname,format_type(a.atttypid,a.atttypmod) type,a.attnotnull,a.atthasdef,a.attidentity from pg_attribute a where a.attrelid=${t.oid} and a.attnum>0 and not a.attisdropped order by a.attnum`);out+=JSON.stringify(t.relname)+': {\n';for(const shape of ['Row','Insert','Update']){out+=shape+': {\n';for(const c of cols)out+=JSON.stringify(c.attname)+(shape==='Update'||shape==='Insert'&&(!c.attnotnull||c.atthasdef||c.attidentity)?'?':'')+': '+type(c.type)+(c.attnotnull?'':' | null')+';\n';out+='};\n';}
const fks=await q(`select c.conname,foreign_table.relname referred,(select array_agg(a.attname order by ord) from unnest(c.conkey) with ordinality k(num,ord) join pg_attribute a on a.attrelid=c.conrelid and a.attnum=k.num) columns,(select array_agg(a.attname order by ord) from unnest(c.confkey) with ordinality k(num,ord) join pg_attribute a on a.attrelid=c.confrelid and a.attnum=k.num) referenced from pg_constraint c join pg_class foreign_table on foreign_table.oid=c.confrelid join pg_namespace n on n.oid=foreign_table.relnamespace where c.conrelid=${t.oid} and c.contype='f' and n.nspname='public' order by c.conname`);
out+='Relationships: ['+fks.map(f=>'{ foreignKeyName: '+JSON.stringify(f.conname)+'; columns: '+JSON.stringify(f.columns)+'; isOneToOne: false; referencedRelation: '+JSON.stringify(f.referred)+'; referencedColumns: '+JSON.stringify(f.referenced)+' }').join(',')+'];\n};\n';}
out+='}; Views: {\n';for(const v of await q("select c.oid,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='v'")){const cols=await q(`select attname,format_type(atttypid,atttypmod) type from pg_attribute where attrelid=${v.oid} and attnum>0 and not attisdropped order by attnum`);out+=JSON.stringify(v.relname)+': { Row: {'+cols.map(c=>JSON.stringify(c.attname)+': '+type(c.type)+' | null').join(';')+'}; Relationships: [] };\n';}
out+='}; Functions: {\n';for(const f of await q("select p.oid,p.proname,p.proargnames,p.proargtypes::oid[] argtypes,p.pronargdefaults,format_type(p.prorettype,null) result from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prorettype<>'trigger'::regtype order by p.proname")){let args=[];for(let i=0;i<f.argtypes.length;i++){const t=(await q(`select format_type(${f.argtypes[i]},null) type`))[0].type;args.push(JSON.stringify(f.proargnames?.[i]??'arg'+i)+(i>=f.argtypes.length-f.pronargdefaults?'?':'')+': '+type(t));}out+=JSON.stringify(f.proname)+': { Args: '+(args.length?'{'+args.join(';')+'}':'Record<PropertyKey, never>')+'; Returns: '+type(f.result)+' };\n';}
out+='}; Enums: {\n'+enums.map(e=>JSON.stringify(e.typname)+': '+e.labels.map(JSON.stringify).join(' | ')+';').join('\n')+'\n}; CompositeTypes: Record<never, never>; }; };\n';out=out.replace('Views: {\n}; Functions:','Views: Record<never, never>; Functions:');await writeFile('types/database.ts',out);await db.close();
