-- Academic integrity and immutable branch links.
alter table public."academic_assessments" add constraint "academic_assessments_pkey" PRIMARY KEY (id);
alter table public."academic_assessments" add constraint "academic_assessments_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."academic_assessments" add constraint "academic_assessments_check" CHECK ((status = 'DRAFT'::text) = (published_at IS NULL) OR status = 'CANCELLED'::text);
alter table public."academic_assessments" add constraint "academic_assessments_max_marks_check" CHECK (max_marks > 0::numeric AND max_marks <= 1000::numeric);
alter table public."academic_assessments" add constraint "academic_assessments_status_check" CHECK (status = ANY (ARRAY['DRAFT'::text, 'PUBLISHED'::text, 'CANCELLED'::text]));
alter table public."academic_assessments" add constraint "academic_assessments_title_check" CHECK (length(btrim(title)) >= 3 AND length(btrim(title)) <= 180);
alter table public."academic_groups" add constraint "academic_groups_pkey" PRIMARY KEY (id);
alter table public."academic_groups" add constraint "academic_groups_organization_id_code_key" UNIQUE (scope_branch_id, organization_id, code);
alter table public."academic_groups" add constraint "academic_groups_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."academic_rooms" add constraint "academic_rooms_pkey" PRIMARY KEY (id);
alter table public."academic_rooms" add constraint "academic_rooms_branch_id_name_key" UNIQUE (scope_branch_id, branch_id, name);
alter table public."academic_rooms" add constraint "academic_rooms_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."academic_rooms" add constraint "academic_rooms_capacity_check" CHECK (capacity > 0);
alter table public."academic_rooms" add constraint "academic_rooms_name_check" CHECK (length(btrim(name)) >= 2);
alter table public."academic_routines" add constraint "academic_routines_pkey" PRIMARY KEY (id);
alter table public."academic_routines" add constraint "academic_routines_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."academic_routines" add constraint "academic_routines_check" CHECK (end_time > start_time);
alter table public."academic_routines" add constraint "academic_routines_check1" CHECK (ends_on >= starts_on);
alter table public."academic_routines" add constraint "academic_routines_weekday_check" CHECK (weekday >= 0 AND weekday <= 6);
alter table public."academic_years" add constraint "academic_years_pkey" PRIMARY KEY (id);
alter table public."academic_years" add constraint "academic_years_organization_id_name_key" UNIQUE (scope_branch_id, organization_id, name);
alter table public."academic_years" add constraint "academic_years_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."academic_years" add constraint "academic_years_check" CHECK (ends_on >= starts_on);
alter table public."admission_cases" add constraint "admission_cases_pkey" PRIMARY KEY (id);
alter table public."admission_cases" add constraint "admission_cases_admission_no_key" UNIQUE (admission_no);
alter table public."admission_cases" add constraint "admission_cases_enrollment_id_key" UNIQUE (enrollment_id);
alter table public."admission_cases" add constraint "admission_cases_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."admission_cases" add constraint "admission_cases_status_check" CHECK (status = ANY (ARRAY['DRAFT'::text, 'READY'::text, 'ACCEPTED'::text, 'ACTIVE_ENROLLMENT'::text, 'CANCELLED'::text, 'CLOSED_ENROLLMENT'::text]));
alter table public."admission_command_keys" add constraint "admission_command_keys_pkey" PRIMARY KEY (request_id);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receipts_pkey" PRIMARY KEY (id);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receipts_admission_id_version_key" UNIQUE (admission_id, version);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receipts_request_id_key" UNIQUE (request_id);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receipts_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receip_physical_copy_reference_check" CHECK (physical_copy_reference IS NULL OR length(physical_copy_reference) <= 160);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receipts_reason_check" CHECK (length(TRIM(BOTH FROM reason)) >= 5);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receipts_version_check" CHECK (version > 0);
alter table public."approval_requests" add constraint "approval_requests_pkey" PRIMARY KEY (id);
alter table public."approval_requests" add constraint "approval_requests_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."approval_requests" add constraint "approval_requests_check" CHECK (status = 'PENDING'::approval_status AND decided_by IS NULL AND decided_at IS NULL OR status <> 'PENDING'::approval_status);
alter table public."areas" add constraint "areas_pkey" PRIMARY KEY (id);
alter table public."areas" add constraint "areas_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_pkey" PRIMARY KEY (id);
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_assessment_id_revision_key" UNIQUE (assessment_id, revision);
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_check" CHECK ((status = ANY (ARRAY['APPROVED'::text, 'REJECTED'::text])) = (reviewer_id IS NOT NULL));
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_revision_check" CHECK (revision > 0);
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_status_check" CHECK (status = ANY (ARRAY['DRAFT'::text, 'SUBMITTED'::text, 'APPROVED'::text, 'REJECTED'::text]));
alter table public."attendance_submissions" add constraint "attendance_submissions_pkey" PRIMARY KEY (id);
alter table public."attendance_submissions" add constraint "attendance_submissions_approval_id_key" UNIQUE (approval_id);
alter table public."attendance_submissions" add constraint "attendance_submissions_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."attendance_submissions" add constraint "attendance_submissions_session_id_revision_key" UNIQUE (session_id, revision);
alter table public."attendance_submissions" add constraint "attendance_submissions_status_check" CHECK (status = ANY (ARRAY['DRAFT'::text, 'SUBMITTED'::text, 'APPROVED'::text, 'REJECTED'::text]));
alter table public."audit_events" add constraint "audit_events_pkey" PRIMARY KEY (id);
alter table public."audit_events" add constraint "audit_events_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."batches" add constraint "batches_pkey" PRIMARY KEY (id);
alter table public."batches" add constraint "batches_organization_id_academic_year_id_code_key" UNIQUE (scope_branch_id, organization_id, academic_year_id, code);
alter table public."batches" add constraint "batches_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."batches" add constraint "batches_capacity_check" CHECK (capacity > 0);
alter table public."branch_memberships" add constraint "branch_memberships_pkey" PRIMARY KEY (branch_id, user_id);
alter table public."branch_open_commands" add constraint "branch_open_commands_pkey" PRIMARY KEY (user_id, request_id);
alter table public."branch_owners" add constraint "branch_owners_pkey" PRIMARY KEY (organization_id);
alter table public."branches" add constraint "branches_pkey" PRIMARY KEY (id);
alter table public."branches" add constraint "branches_organization_id_code_key" UNIQUE (organization_id, code);
alter table public."branches" add constraint "branches_slug_key" UNIQUE (slug);
alter table public."business_rule_versions" add constraint "business_rule_versions_pkey" PRIMARY KEY (id);
alter table public."business_rule_versions" add constraint "business_rule_versions_domain_rule_key_version_key" UNIQUE (scope_branch_id, domain, rule_key, version);
alter table public."business_rule_versions" add constraint "business_rule_versions_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."business_rule_versions" add constraint "business_rule_versions_check" CHECK (effective_to IS NULL OR effective_to >= effective_from);
alter table public."class_logs" add constraint "class_logs_pkey" PRIMARY KEY (id);
alter table public."class_logs" add constraint "class_logs_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."class_logs" add constraint "class_logs_session_id_revision_key" UNIQUE (session_id, revision);
alter table public."class_logs" add constraint "class_logs_check" CHECK (status = 'DRAFT'::text AND submitted_at IS NULL OR status = 'SUBMITTED'::text AND submitted_at IS NOT NULL);
alter table public."class_logs" add constraint "class_logs_revision_check" CHECK (revision > 0);
alter table public."class_logs" add constraint "class_logs_status_check" CHECK (status = ANY (ARRAY['DRAFT'::text, 'SUBMITTED'::text, 'APPROVED'::text, 'REJECTED'::text]));
alter table public."class_sessions" add constraint "class_sessions_pkey" PRIMARY KEY (id);
alter table public."class_sessions" add constraint "class_sessions_routine_id_session_date_key" UNIQUE (routine_id, session_date);
alter table public."class_sessions" add constraint "class_sessions_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."class_sessions" add constraint "class_sessions_check" CHECK (ends_at > starts_at);
alter table public."class_sessions" add constraint "class_sessions_status_check" CHECK (status = ANY (ARRAY['SCHEDULED'::text, 'CANCELLED'::text]));
alter table public."classes" add constraint "classes_pkey" PRIMARY KEY (id);
alter table public."classes" add constraint "classes_organization_id_code_key" UNIQUE (scope_branch_id, organization_id, code);
alter table public."classes" add constraint "classes_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."curriculum_versions" add constraint "curriculum_versions_pkey" PRIMARY KEY (id);
alter table public."curriculum_versions" add constraint "curriculum_versions_batch_id_subject_id_version_key" UNIQUE (batch_id, subject_id, version);
alter table public."curriculum_versions" add constraint "curriculum_versions_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_pkey" PRIMARY KEY (id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_from_enrollment_id_key" UNIQUE (from_enrollment_id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_to_enrollment_id_key" UNIQUE (to_enrollment_id);
alter table public."enrollments" add constraint "enrollments_pkey" PRIMARY KEY (id);
alter table public."enrollments" add constraint "enrollments_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."enrollments" add constraint "enrollments_check" CHECK (ended_on IS NULL OR ended_on >= admission_date);
alter table public."guardian_relationships" add constraint "guardian_relationships_pkey" PRIMARY KEY (id);
alter table public."guardian_relationships" add constraint "guardian_relationships_organization_id_code_key" UNIQUE (scope_branch_id, organization_id, code);
alter table public."guardian_relationships" add constraint "guardian_relationships_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."guardians" add constraint "guardians_pkey" PRIMARY KEY (id);
alter table public."guardians" add constraint "guardians_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."homework_checks" add constraint "homework_checks_pkey" PRIMARY KEY (id);
alter table public."homework_checks" add constraint "homework_checks_class_log_id_enrollment_id_revision_key" UNIQUE (class_log_id, enrollment_id, revision);
alter table public."homework_checks" add constraint "homework_checks_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."homework_checks" add constraint "homework_checks_feedback_check" CHECK (length(feedback) <= 1000);
alter table public."homework_checks" add constraint "homework_checks_revision_check" CHECK (revision > 0);
alter table public."homework_checks" add constraint "homework_checks_status_check" CHECK (status = ANY (ARRAY['NOT_SUBMITTED'::text, 'NEEDS_WORK'::text, 'COMPLETE'::text]));
alter table public."lead_sources" add constraint "lead_sources_pkey" PRIMARY KEY (id);
alter table public."lead_sources" add constraint "lead_sources_organization_id_code_key" UNIQUE (scope_branch_id, organization_id, code);
alter table public."lead_sources" add constraint "lead_sources_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."organizations" add constraint "organizations_pkey" PRIMARY KEY (id);
alter table public."organizations" add constraint "organizations_code_key" UNIQUE (code);
alter table public."permissions" add constraint "permissions_pkey" PRIMARY KEY (id);
alter table public."permissions" add constraint "permissions_code_key" UNIQUE (code);
alter table public."profiles" add constraint "profiles_pkey" PRIMARY KEY (id);
alter table public."programme_offering_subjects" add constraint "programme_offering_subjects_pkey" PRIMARY KEY (offering_id, subject_id);
alter table public."programme_offerings" add constraint "programme_offerings_pkey" PRIMARY KEY (id);
alter table public."programme_offerings" add constraint "programme_offerings_organization_id_academic_year_id_code_key" UNIQUE (scope_branch_id, organization_id, academic_year_id, code);
alter table public."programme_offerings" add constraint "programme_offerings_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."programme_offerings" add constraint "programme_offerings_code_check" CHECK (length(btrim(code)) >= 2 AND length(btrim(code)) <= 40);
alter table public."programme_offerings" add constraint "programme_offerings_name_check" CHECK (length(btrim(name)) >= 2 AND length(btrim(name)) <= 160);
alter table public."programs" add constraint "programs_pkey" PRIMARY KEY (id);
alter table public."programs" add constraint "programs_organization_id_code_key" UNIQUE (scope_branch_id, organization_id, code);
alter table public."programs" add constraint "programs_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."prospect_followups" add constraint "prospect_followups_pkey" PRIMARY KEY (id);
alter table public."prospect_followups" add constraint "prospect_followups_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."prospect_followups" add constraint "prospect_followup_type_check" CHECK (followup_type = ANY (ARRAY['CALL'::text, 'WHATSAPP'::text, 'IN_PERSON'::text, 'COUNSELLING'::text, 'TRIAL'::text, 'OTHER'::text]));
alter table public."prospect_program_interests" add constraint "prospect_program_interests_pkey" PRIMARY KEY (prospect_id, program_id);
alter table public."prospect_subject_interests" add constraint "prospect_subject_interests_pkey" PRIMARY KEY (prospect_id, subject_id);
alter table public."prospects" add constraint "prospects_pkey" PRIMARY KEY (id);
alter table public."prospects" add constraint "prospects_prospect_no_key" UNIQUE (prospect_no);
alter table public."prospects" add constraint "prospects_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."prospects" add constraint "prospects_submission_intent_check" CHECK (submission_intent = ANY (ARRAY['interest'::text, 'admission'::text]));
alter table public."question_bank_items" add constraint "question_bank_items_pkey" PRIMARY KEY (id);
alter table public."question_bank_items" add constraint "question_bank_items_root_id_revision_key" UNIQUE (root_id, revision);
alter table public."question_bank_items" add constraint "question_bank_items_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."question_bank_items" add constraint "question_bank_items_answer_key_check" CHECK (length(btrim(answer_key)) >= 1 AND length(btrim(answer_key)) <= 1500);
alter table public."question_bank_items" add constraint "question_bank_items_check" CHECK ((status = ANY (ARRAY['APPROVED'::text, 'REJECTED'::text])) = (reviewer_id IS NOT NULL));
alter table public."question_bank_items" add constraint "question_bank_items_difficulty_check" CHECK (difficulty = ANY (ARRAY['FOUNDATION'::text, 'STANDARD'::text, 'ADVANCED'::text]));
alter table public."question_bank_items" add constraint "question_bank_items_explanation_check" CHECK (explanation IS NULL OR length(explanation) <= 3000);
alter table public."question_bank_items" add constraint "question_bank_items_prompt_check" CHECK (length(btrim(prompt)) >= 10 AND length(btrim(prompt)) <= 3000);
alter table public."question_bank_items" add constraint "question_bank_items_question_type_check" CHECK (question_type = ANY (ARRAY['MCQ'::text, 'SHORT_ANSWER'::text]));
alter table public."question_bank_items" add constraint "question_bank_items_revision_check" CHECK (revision > 0);
alter table public."question_bank_items" add constraint "question_bank_items_status_check" CHECK (status = ANY (ARRAY['DRAFT'::text, 'SUBMITTED'::text, 'APPROVED'::text, 'REJECTED'::text]));
alter table public."question_bank_items" add constraint "question_bank_items_topic_check" CHECK (length(btrim(topic)) >= 2 AND length(btrim(topic)) <= 180);
alter table public."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY (role_id, permission_id);
alter table public."schools" add constraint "schools_pkey" PRIMARY KEY (id);
alter table public."schools" add constraint "schools_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."staff" add constraint "staff_pkey" PRIMARY KEY (id);
alter table public."staff" add constraint "staff_profile_id_key" UNIQUE (scope_branch_id, profile_id);
alter table public."staff" add constraint "staff_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."staff" add constraint "staff_staff_no_key" UNIQUE (staff_no);
alter table public."staff" add constraint "staff_check" CHECK (left_on IS NULL OR joined_on IS NULL OR left_on >= joined_on);
alter table public."staff_access_requests" add constraint "staff_access_requests_pkey" PRIMARY KEY (id);
alter table public."staff_access_requests" add constraint "staff_access_requests_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."staff_access_requests" add constraint "staff_access_requests_assigned_role_check" CHECK (assigned_role = ANY (ARRAY['ADMIN'::text, 'OPERATOR'::text, 'TEACHER'::text, 'ACCOUNTANT'::text]));
alter table public."staff_access_requests" add constraint "staff_access_requests_requested_role_check" CHECK (requested_role = ANY (ARRAY['ADMIN'::text, 'OPERATOR'::text, 'TEACHER'::text, 'ACCOUNTANT'::text]));
alter table public."staff_access_requests" add constraint "staff_access_requests_status_check" CHECK (status = ANY (ARRAY['PENDING'::text, 'VERIFIED'::text, 'INVITED'::text, 'ACTIVE'::text, 'DECLINED'::text, 'INACTIVE'::text]));
alter table public."staff_admission_intake_requests" add constraint "staff_admission_intake_requests_pkey" PRIMARY KEY (request_id);
alter table public."staff_attendance_records" add constraint "staff_attendance_records_pkey" PRIMARY KEY (id);
alter table public."staff_attendance_records" add constraint "staff_attendance_records_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."staff_attendance_records" add constraint "staff_attendance_records_staff_id_work_date_key" UNIQUE (staff_id, work_date);
alter table public."staff_attendance_records" add constraint "staff_attendance_records_break_minutes_check" CHECK (break_minutes >= 0 AND break_minutes <= 1440);
alter table public."staff_attendance_records" add constraint "staff_attendance_records_reason_check" CHECK (length(btrim(reason)) >= 5);
alter table public."staff_attendance_records" add constraint "staff_attendance_records_status_check" CHECK (status = ANY (ARRAY['PRESENT'::text, 'ABSENT'::text, 'LEAVE'::text, 'HOLIDAY'::text]));
alter table public."staff_role_assignments" add constraint "staff_role_assignments_pkey" PRIMARY KEY (id);
alter table public."staff_role_assignments" add constraint "staff_role_assignments_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."staff_role_assignments" add constraint "staff_role_assignments_check" CHECK (effective_to IS NULL OR effective_to >= effective_from);
alter table public."staff_roles" add constraint "staff_roles_pkey" PRIMARY KEY (id);
alter table public."staff_roles" add constraint "staff_roles_code_key" UNIQUE (code);
alter table public."staff_subject_assignments" add constraint "staff_subject_assignments_pkey" PRIMARY KEY (id);
alter table public."staff_subject_assignments" add constraint "staff_subject_assignments_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."staff_subject_assignments" add constraint "staff_subject_assignments_check" CHECK (effective_to IS NULL OR effective_to >= effective_from);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_pkey" PRIMARY KEY (id);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_blocker_check" CHECK (length(blocker) <= 2000);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_check" CHECK ((status <> ALL (ARRAY['SUBMITTED'::text, 'COMPLETED'::text])) OR progress = 100);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_check1" CHECK ((status = 'COMPLETED'::text) = (completed_at IS NOT NULL));
alter table public."staff_work_tasks" add constraint "staff_work_tasks_instructions_check" CHECK (length(instructions) <= 4000);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_progress_check" CHECK (progress >= 0 AND progress <= 100);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_status_check" CHECK (status = ANY (ARRAY['OPEN'::text, 'IN_PROGRESS'::text, 'SUBMITTED'::text, 'COMPLETED'::text, 'CANCELLED'::text]));
alter table public."staff_work_tasks" add constraint "staff_work_tasks_title_check" CHECK (length(btrim(title)) >= 3 AND length(btrim(title)) <= 160);
alter table public."student_guardians" add constraint "student_guardians_pkey" PRIMARY KEY (id);
alter table public."student_guardians" add constraint "student_guardians_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."student_guardians" add constraint "student_guardians_student_id_guardian_id_key" UNIQUE (student_id, guardian_id);
alter table public."student_merges" add constraint "student_merges_pkey" PRIMARY KEY (id);
alter table public."student_merges" add constraint "student_merges_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."student_merges" add constraint "student_merges_source_id_key" UNIQUE (source_id);
alter table public."student_merges" add constraint "student_merges_check" CHECK (source_id <> target_id);
alter table public."students" add constraint "students_pkey" PRIMARY KEY (id);
alter table public."students" add constraint "students_created_from_prospect_id_key" UNIQUE (created_from_prospect_id);
alter table public."students" add constraint "students_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."students" add constraint "students_student_no_key" UNIQUE (student_no);
alter table public."students" add constraint "no_self_merge" CHECK (merged_into_id IS NULL OR merged_into_id <> id);
alter table public."subjects" add constraint "subjects_pkey" PRIMARY KEY (id);
alter table public."subjects" add constraint "subjects_organization_id_code_key" UNIQUE (scope_branch_id, organization_id, code);
alter table public."subjects" add constraint "subjects_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."system_roles" add constraint "system_roles_pkey" PRIMARY KEY (id);
alter table public."system_roles" add constraint "system_roles_code_key" UNIQUE (code);
alter table public."user_role_assignments" add constraint "user_role_assignments_pkey" PRIMARY KEY (id);
alter table public."user_role_assignments" add constraint "user_role_assignments_scope_branch_id_id_key" UNIQUE (scope_branch_id, id);
alter table public."user_role_assignments" add constraint "user_role_assignments_check" CHECK (effective_to IS NULL OR effective_to >= effective_from);
alter table public."academic_assessments" add constraint "academic_assessments_author_id_fkey" FOREIGN KEY (author_id) REFERENCES profiles(id);
alter table public."academic_assessments" add constraint "academic_assessments_batch_id_fkey" FOREIGN KEY (batch_id) REFERENCES batches(id);
alter table public."academic_assessments" add constraint "academic_assessments_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."academic_assessments" add constraint "academic_assessments_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id);
alter table public."academic_assessments" add constraint "scope_b5f58cf685ed51df37c10857" FOREIGN KEY (scope_branch_id, subject_id) REFERENCES subjects(scope_branch_id, id);
alter table public."academic_assessments" add constraint "scope_e02ac7f02409cfb409728185" FOREIGN KEY (scope_branch_id, batch_id) REFERENCES batches(scope_branch_id, id);
alter table public."academic_groups" add constraint "academic_groups_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."academic_groups" add constraint "academic_groups_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."academic_rooms" add constraint "academic_rooms_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."academic_rooms" add constraint "academic_rooms_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."academic_rooms" add constraint "academic_rooms_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."academic_routines" add constraint "academic_routines_batch_id_fkey" FOREIGN KEY (batch_id) REFERENCES batches(id);
alter table public."academic_routines" add constraint "academic_routines_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."academic_routines" add constraint "academic_routines_room_id_fkey" FOREIGN KEY (room_id) REFERENCES academic_rooms(id);
alter table public."academic_routines" add constraint "academic_routines_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."academic_routines" add constraint "academic_routines_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id);
alter table public."academic_routines" add constraint "academic_routines_teacher_id_fkey" FOREIGN KEY (teacher_id) REFERENCES staff(id);
alter table public."academic_routines" add constraint "scope_59c76c3ebb926cd268e5400e" FOREIGN KEY (scope_branch_id, room_id) REFERENCES academic_rooms(scope_branch_id, id);
alter table public."academic_routines" add constraint "scope_611d3a0eb2cbfd52b8d90ff1" FOREIGN KEY (scope_branch_id, subject_id) REFERENCES subjects(scope_branch_id, id);
alter table public."academic_routines" add constraint "scope_aaab8f286c95e147643d1905" FOREIGN KEY (scope_branch_id, batch_id) REFERENCES batches(scope_branch_id, id);
alter table public."academic_routines" add constraint "scope_ac9d9c2dd64bafd4f449b9a4" FOREIGN KEY (scope_branch_id, teacher_id) REFERENCES staff(scope_branch_id, id);
alter table public."academic_years" add constraint "academic_years_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."academic_years" add constraint "academic_years_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."admission_cases" add constraint "admission_cases_activation_policy_version_id_fkey" FOREIGN KEY (activation_policy_version_id) REFERENCES business_rule_versions(id);
alter table public."admission_cases" add constraint "admission_cases_batch_id_fkey" FOREIGN KEY (batch_id) REFERENCES batches(id);
alter table public."admission_cases" add constraint "admission_cases_capacity_policy_version_id_fkey" FOREIGN KEY (capacity_policy_version_id) REFERENCES business_rule_versions(id);
alter table public."admission_cases" add constraint "admission_cases_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."admission_cases" add constraint "admission_cases_enrollment_id_fkey" FOREIGN KEY (enrollment_id) REFERENCES enrollments(id);
alter table public."admission_cases" add constraint "admission_cases_origin_prospect_id_fkey" FOREIGN KEY (origin_prospect_id) REFERENCES prospects(id);
alter table public."admission_cases" add constraint "admission_cases_prospect_id_fkey" FOREIGN KEY (prospect_id) REFERENCES prospects(id);
alter table public."admission_cases" add constraint "admission_cases_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."admission_cases" add constraint "admission_cases_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id);
alter table public."admission_cases" add constraint "scope_37fb5fbd2ddc399fc7d3a840" FOREIGN KEY (scope_branch_id, origin_prospect_id) REFERENCES prospects(scope_branch_id, id);
alter table public."admission_cases" add constraint "scope_6731029347829530ba1da3e2" FOREIGN KEY (scope_branch_id, activation_policy_version_id) REFERENCES business_rule_versions(scope_branch_id, id);
alter table public."admission_cases" add constraint "scope_67f4c4bae7fed1266beaacbe" FOREIGN KEY (scope_branch_id, student_id) REFERENCES students(scope_branch_id, id);
alter table public."admission_cases" add constraint "scope_76e6ac29825ff50013e38ba5" FOREIGN KEY (scope_branch_id, prospect_id) REFERENCES prospects(scope_branch_id, id);
alter table public."admission_cases" add constraint "scope_8ebd7caf5703986456e2411e" FOREIGN KEY (scope_branch_id, capacity_policy_version_id) REFERENCES business_rule_versions(scope_branch_id, id);
alter table public."admission_cases" add constraint "scope_a8febaf584b39709054fe2e9" FOREIGN KEY (scope_branch_id, batch_id) REFERENCES batches(scope_branch_id, id);
alter table public."admission_cases" add constraint "scope_b98bfd22f1f741bcdf3a460f" FOREIGN KEY (scope_branch_id, enrollment_id) REFERENCES enrollments(scope_branch_id, id);
alter table public."admission_command_keys" add constraint "admission_command_keys_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES profiles(id);
alter table public."admission_command_keys" add constraint "admission_command_keys_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receipts_admission_id_fkey" FOREIGN KEY (admission_id) REFERENCES admission_cases(id);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receipts_received_by_fkey" FOREIGN KEY (received_by) REFERENCES profiles(id);
alter table public."admission_physical_consent_receipts" add constraint "admission_physical_consent_receipts_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."admission_physical_consent_receipts" add constraint "scope_c72e5b8d962d0ed4b8de1b24" FOREIGN KEY (scope_branch_id, admission_id) REFERENCES admission_cases(scope_branch_id, id);
alter table public."approval_requests" add constraint "approval_requests_decided_by_fkey" FOREIGN KEY (decided_by) REFERENCES profiles(id);
alter table public."approval_requests" add constraint "approval_requests_requested_by_fkey" FOREIGN KEY (requested_by) REFERENCES profiles(id);
alter table public."approval_requests" add constraint "approval_requests_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."areas" add constraint "areas_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."areas" add constraint "areas_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES areas(id);
alter table public."areas" add constraint "areas_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."areas" add constraint "scope_4d8574c822da893b8e8ab320" FOREIGN KEY (scope_branch_id, parent_id) REFERENCES areas(scope_branch_id, id);
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_assessment_id_fkey" FOREIGN KEY (assessment_id) REFERENCES academic_assessments(id);
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_author_id_fkey" FOREIGN KEY (author_id) REFERENCES profiles(id);
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_reviewer_id_fkey" FOREIGN KEY (reviewer_id) REFERENCES profiles(id);
alter table public."assessment_result_submissions" add constraint "assessment_result_submissions_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."assessment_result_submissions" add constraint "scope_4a1e306d73f8f759dbe231e6" FOREIGN KEY (scope_branch_id, assessment_id) REFERENCES academic_assessments(scope_branch_id, id);
alter table public."attendance_submissions" add constraint "attendance_submissions_approval_id_fkey" FOREIGN KEY (approval_id) REFERENCES approval_requests(id);
alter table public."attendance_submissions" add constraint "attendance_submissions_recorded_by_fkey" FOREIGN KEY (recorded_by) REFERENCES profiles(id);
alter table public."attendance_submissions" add constraint "attendance_submissions_reviewer_id_fkey" FOREIGN KEY (reviewer_id) REFERENCES profiles(id);
alter table public."attendance_submissions" add constraint "attendance_submissions_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."attendance_submissions" add constraint "attendance_submissions_session_id_fkey" FOREIGN KEY (session_id) REFERENCES class_sessions(id);
alter table public."attendance_submissions" add constraint "scope_574683d759a3da659a2663e5" FOREIGN KEY (scope_branch_id, session_id) REFERENCES class_sessions(scope_branch_id, id);
alter table public."attendance_submissions" add constraint "scope_a263c321bd661531072d09b5" FOREIGN KEY (scope_branch_id, approval_id) REFERENCES approval_requests(scope_branch_id, id);
alter table public."audit_events" add constraint "audit_events_actor_profile_id_fkey" FOREIGN KEY (actor_profile_id) REFERENCES profiles(id);
alter table public."audit_events" add constraint "audit_events_actor_staff_id_fkey" FOREIGN KEY (actor_staff_id) REFERENCES staff(id);
alter table public."audit_events" add constraint "audit_events_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."audit_events" add constraint "audit_events_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."audit_events" add constraint "scope_a11a61dd0efc44843ac95bad" FOREIGN KEY (scope_branch_id, actor_staff_id) REFERENCES staff(scope_branch_id, id);
alter table public."batches" add constraint "batches_academic_year_id_fkey" FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
alter table public."batches" add constraint "batches_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."batches" add constraint "batches_capacity_policy_version_id_fkey" FOREIGN KEY (capacity_policy_version_id) REFERENCES business_rule_versions(id);
alter table public."batches" add constraint "batches_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id);
alter table public."batches" add constraint "batches_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."batches" add constraint "batches_offering_id_fkey" FOREIGN KEY (offering_id) REFERENCES programme_offerings(id);
alter table public."batches" add constraint "batches_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."batches" add constraint "batches_program_id_fkey" FOREIGN KEY (program_id) REFERENCES programs(id);
alter table public."batches" add constraint "batches_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."batches" add constraint "scope_4dc698192a26c8bb9cd101bc" FOREIGN KEY (scope_branch_id, academic_year_id) REFERENCES academic_years(scope_branch_id, id);
alter table public."batches" add constraint "scope_a95aae1cdf0b3528a1d10941" FOREIGN KEY (scope_branch_id, offering_id) REFERENCES programme_offerings(scope_branch_id, id);
alter table public."batches" add constraint "scope_bada60e84d9bf179c4508e0c" FOREIGN KEY (scope_branch_id, program_id) REFERENCES programs(scope_branch_id, id);
alter table public."batches" add constraint "scope_c3089fc717ca26ca797d26b5" FOREIGN KEY (scope_branch_id, capacity_policy_version_id) REFERENCES business_rule_versions(scope_branch_id, id);
alter table public."batches" add constraint "scope_d09c084cb727b7b79f63e930" FOREIGN KEY (scope_branch_id, class_id) REFERENCES classes(scope_branch_id, id);
alter table public."branch_memberships" add constraint "branch_memberships_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."branch_memberships" add constraint "branch_memberships_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public."branch_open_commands" add constraint "branch_open_commands_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public."branch_owners" add constraint "branch_owners_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."branch_owners" add constraint "branch_owners_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public."branches" add constraint "branches_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."business_rule_versions" add constraint "business_rule_versions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."business_rule_versions" add constraint "business_rule_versions_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."class_logs" add constraint "class_logs_authored_by_fkey" FOREIGN KEY (authored_by) REFERENCES profiles(id);
alter table public."class_logs" add constraint "class_logs_previous_log_id_fkey" FOREIGN KEY (previous_log_id) REFERENCES class_logs(id);
alter table public."class_logs" add constraint "class_logs_reviewer_id_fkey" FOREIGN KEY (reviewer_id) REFERENCES profiles(id);
alter table public."class_logs" add constraint "class_logs_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."class_logs" add constraint "class_logs_session_id_fkey" FOREIGN KEY (session_id) REFERENCES class_sessions(id);
alter table public."class_logs" add constraint "scope_01cc255e29661edc6412bfc4" FOREIGN KEY (scope_branch_id, session_id) REFERENCES class_sessions(scope_branch_id, id);
alter table public."class_logs" add constraint "scope_4ce0f80eaa36d7cdea5e6375" FOREIGN KEY (scope_branch_id, previous_log_id) REFERENCES class_logs(scope_branch_id, id);
alter table public."class_sessions" add constraint "class_sessions_batch_id_fkey" FOREIGN KEY (batch_id) REFERENCES batches(id);
alter table public."class_sessions" add constraint "class_sessions_cancelled_by_fkey" FOREIGN KEY (cancelled_by) REFERENCES profiles(id);
alter table public."class_sessions" add constraint "class_sessions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."class_sessions" add constraint "class_sessions_curriculum_version_id_fkey" FOREIGN KEY (curriculum_version_id) REFERENCES curriculum_versions(id);
alter table public."class_sessions" add constraint "class_sessions_room_id_fkey" FOREIGN KEY (room_id) REFERENCES academic_rooms(id);
alter table public."class_sessions" add constraint "class_sessions_routine_id_fkey" FOREIGN KEY (routine_id) REFERENCES academic_routines(id);
alter table public."class_sessions" add constraint "class_sessions_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."class_sessions" add constraint "class_sessions_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id);
alter table public."class_sessions" add constraint "class_sessions_teacher_id_fkey" FOREIGN KEY (teacher_id) REFERENCES staff(id);
alter table public."class_sessions" add constraint "scope_06d7d413d8b2a752edecf79b" FOREIGN KEY (scope_branch_id, batch_id) REFERENCES batches(scope_branch_id, id);
alter table public."class_sessions" add constraint "scope_30781efec50ebd05eeb9e6df" FOREIGN KEY (scope_branch_id, room_id) REFERENCES academic_rooms(scope_branch_id, id);
alter table public."class_sessions" add constraint "scope_398e3c1b4f313018a63cf8ed" FOREIGN KEY (scope_branch_id, subject_id) REFERENCES subjects(scope_branch_id, id);
alter table public."class_sessions" add constraint "scope_7a7c65102808e97240319c9c" FOREIGN KEY (scope_branch_id, teacher_id) REFERENCES staff(scope_branch_id, id);
alter table public."class_sessions" add constraint "scope_7be3d38a67f9a5a855153177" FOREIGN KEY (scope_branch_id, routine_id) REFERENCES academic_routines(scope_branch_id, id);
alter table public."class_sessions" add constraint "scope_ffbb52d3565427150a29ba02" FOREIGN KEY (scope_branch_id, curriculum_version_id) REFERENCES curriculum_versions(scope_branch_id, id);
alter table public."classes" add constraint "classes_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."classes" add constraint "classes_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."curriculum_versions" add constraint "curriculum_versions_batch_id_fkey" FOREIGN KEY (batch_id) REFERENCES batches(id);
alter table public."curriculum_versions" add constraint "curriculum_versions_published_by_fkey" FOREIGN KEY (published_by) REFERENCES profiles(id);
alter table public."curriculum_versions" add constraint "curriculum_versions_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."curriculum_versions" add constraint "curriculum_versions_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id);
alter table public."curriculum_versions" add constraint "scope_a93ee8fe9ad9dcc08c2fe209" FOREIGN KEY (scope_branch_id, subject_id) REFERENCES subjects(scope_branch_id, id);
alter table public."curriculum_versions" add constraint "scope_aba8f9483b8f0849ad245b3a" FOREIGN KEY (scope_branch_id, batch_id) REFERENCES batches(scope_branch_id, id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_admission_id_fkey" FOREIGN KEY (admission_id) REFERENCES admission_cases(id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_authorized_by_fkey" FOREIGN KEY (authorized_by) REFERENCES profiles(id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_capacity_policy_version_id_fkey" FOREIGN KEY (capacity_policy_version_id) REFERENCES business_rule_versions(id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_from_batch_id_fkey" FOREIGN KEY (from_batch_id) REFERENCES batches(id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_from_enrollment_id_fkey" FOREIGN KEY (from_enrollment_id) REFERENCES enrollments(id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_to_batch_id_fkey" FOREIGN KEY (to_batch_id) REFERENCES batches(id);
alter table public."enrollment_transfers" add constraint "enrollment_transfers_to_enrollment_id_fkey" FOREIGN KEY (to_enrollment_id) REFERENCES enrollments(id);
alter table public."enrollment_transfers" add constraint "scope_201d6f34e55aa1c293638ce6" FOREIGN KEY (scope_branch_id, capacity_policy_version_id) REFERENCES business_rule_versions(scope_branch_id, id);
alter table public."enrollment_transfers" add constraint "scope_490cb0f3ebe6db3bae532008" FOREIGN KEY (scope_branch_id, admission_id) REFERENCES admission_cases(scope_branch_id, id);
alter table public."enrollment_transfers" add constraint "scope_72d537e34f854adff980f601" FOREIGN KEY (scope_branch_id, student_id) REFERENCES students(scope_branch_id, id);
alter table public."enrollment_transfers" add constraint "scope_7d9393c5531f462d1ff0ac2a" FOREIGN KEY (scope_branch_id, from_batch_id) REFERENCES batches(scope_branch_id, id);
alter table public."enrollment_transfers" add constraint "scope_89df8e62e4ec94916d2b4128" FOREIGN KEY (scope_branch_id, to_batch_id) REFERENCES batches(scope_branch_id, id);
alter table public."enrollment_transfers" add constraint "scope_c76ef36a338d5b6a8e5945db" FOREIGN KEY (scope_branch_id, from_enrollment_id) REFERENCES enrollments(scope_branch_id, id);
alter table public."enrollment_transfers" add constraint "scope_e0f195d75949ee0c2ad98b88" FOREIGN KEY (scope_branch_id, to_enrollment_id) REFERENCES enrollments(scope_branch_id, id);
alter table public."enrollments" add constraint "enrollments_academic_year_id_fkey" FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
alter table public."enrollments" add constraint "enrollments_batch_id_fkey" FOREIGN KEY (batch_id) REFERENCES batches(id);
alter table public."enrollments" add constraint "enrollments_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."enrollments" add constraint "enrollments_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id);
alter table public."enrollments" add constraint "enrollments_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."enrollments" add constraint "enrollments_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."enrollments" add constraint "enrollments_program_id_fkey" FOREIGN KEY (program_id) REFERENCES programs(id);
alter table public."enrollments" add constraint "enrollments_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."enrollments" add constraint "enrollments_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id);
alter table public."enrollments" add constraint "scope_017879d2c2b824d0663489c4" FOREIGN KEY (scope_branch_id, academic_year_id) REFERENCES academic_years(scope_branch_id, id);
alter table public."enrollments" add constraint "scope_18b529dc941d9c31bd22da68" FOREIGN KEY (scope_branch_id, program_id) REFERENCES programs(scope_branch_id, id);
alter table public."enrollments" add constraint "scope_c1b478b26b8ea82084cfca1c" FOREIGN KEY (scope_branch_id, student_id) REFERENCES students(scope_branch_id, id);
alter table public."enrollments" add constraint "scope_eb265cc55363d52545229cfb" FOREIGN KEY (scope_branch_id, batch_id) REFERENCES batches(scope_branch_id, id);
alter table public."enrollments" add constraint "scope_f4f6f9d528756f11b61b874d" FOREIGN KEY (scope_branch_id, class_id) REFERENCES classes(scope_branch_id, id);
alter table public."guardian_relationships" add constraint "guardian_relationships_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."guardian_relationships" add constraint "guardian_relationships_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."guardians" add constraint "guardians_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."guardians" add constraint "guardians_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."guardians" add constraint "guardians_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."homework_checks" add constraint "homework_checks_class_log_id_fkey" FOREIGN KEY (class_log_id) REFERENCES class_logs(id);
alter table public."homework_checks" add constraint "homework_checks_enrollment_id_fkey" FOREIGN KEY (enrollment_id) REFERENCES enrollments(id);
alter table public."homework_checks" add constraint "homework_checks_recorded_by_fkey" FOREIGN KEY (recorded_by) REFERENCES profiles(id);
alter table public."homework_checks" add constraint "homework_checks_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."homework_checks" add constraint "scope_26faf3652ee810333b29eb71" FOREIGN KEY (scope_branch_id, enrollment_id) REFERENCES enrollments(scope_branch_id, id);
alter table public."homework_checks" add constraint "scope_f176ef45ee96b71ec68a4063" FOREIGN KEY (scope_branch_id, class_log_id) REFERENCES class_logs(scope_branch_id, id);
alter table public."lead_sources" add constraint "lead_sources_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."lead_sources" add constraint "lead_sources_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."organizations" add constraint "organizations_setup_completed_by_fkey" FOREIGN KEY (setup_completed_by) REFERENCES profiles(id);
alter table public."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."programme_offering_subjects" add constraint "programme_offering_subjects_offering_id_fkey" FOREIGN KEY (offering_id) REFERENCES programme_offerings(id) ON DELETE CASCADE;
alter table public."programme_offering_subjects" add constraint "programme_offering_subjects_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."programme_offering_subjects" add constraint "programme_offering_subjects_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id);
alter table public."programme_offering_subjects" add constraint "scope_961a631da130d954c5abd5ce" FOREIGN KEY (scope_branch_id, offering_id) REFERENCES programme_offerings(scope_branch_id, id);
alter table public."programme_offering_subjects" add constraint "scope_d91517319d0a6060e8bc2eec" FOREIGN KEY (scope_branch_id, subject_id) REFERENCES subjects(scope_branch_id, id);
alter table public."programme_offerings" add constraint "programme_offerings_academic_year_id_fkey" FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
alter table public."programme_offerings" add constraint "programme_offerings_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."programme_offerings" add constraint "programme_offerings_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id);
alter table public."programme_offerings" add constraint "programme_offerings_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."programme_offerings" add constraint "programme_offerings_group_id_fkey" FOREIGN KEY (group_id) REFERENCES academic_groups(id);
alter table public."programme_offerings" add constraint "programme_offerings_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."programme_offerings" add constraint "programme_offerings_program_id_fkey" FOREIGN KEY (program_id) REFERENCES programs(id);
alter table public."programme_offerings" add constraint "programme_offerings_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."programme_offerings" add constraint "scope_24953c85ad8e45edacb94c0c" FOREIGN KEY (scope_branch_id, class_id) REFERENCES classes(scope_branch_id, id);
alter table public."programme_offerings" add constraint "scope_ab793ff41d50fe3e11e889d2" FOREIGN KEY (scope_branch_id, group_id) REFERENCES academic_groups(scope_branch_id, id);
alter table public."programme_offerings" add constraint "scope_da9d18c11d4a144778d5915b" FOREIGN KEY (scope_branch_id, program_id) REFERENCES programs(scope_branch_id, id);
alter table public."programme_offerings" add constraint "scope_e0729dcd9488a477e20a769c" FOREIGN KEY (scope_branch_id, academic_year_id) REFERENCES academic_years(scope_branch_id, id);
alter table public."programs" add constraint "programs_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."programs" add constraint "programs_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."prospect_followups" add constraint "prospect_followups_prospect_id_fkey" FOREIGN KEY (prospect_id) REFERENCES prospects(id);
alter table public."prospect_followups" add constraint "prospect_followups_recorded_by_fkey" FOREIGN KEY (recorded_by) REFERENCES profiles(id);
alter table public."prospect_followups" add constraint "prospect_followups_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."prospect_followups" add constraint "scope_b9e36bd30418d4aeb2f85a22" FOREIGN KEY (scope_branch_id, prospect_id) REFERENCES prospects(scope_branch_id, id);
alter table public."prospect_program_interests" add constraint "prospect_program_interests_program_id_fkey" FOREIGN KEY (program_id) REFERENCES programs(id);
alter table public."prospect_program_interests" add constraint "prospect_program_interests_prospect_id_fkey" FOREIGN KEY (prospect_id) REFERENCES prospects(id);
alter table public."prospect_program_interests" add constraint "prospect_program_interests_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."prospect_program_interests" add constraint "scope_0727a36f2ab2b129b70c0e91" FOREIGN KEY (scope_branch_id, program_id) REFERENCES programs(scope_branch_id, id);
alter table public."prospect_program_interests" add constraint "scope_20b9f1b1305a909a2583563f" FOREIGN KEY (scope_branch_id, prospect_id) REFERENCES prospects(scope_branch_id, id);
alter table public."prospect_subject_interests" add constraint "prospect_subject_interests_prospect_id_fkey" FOREIGN KEY (prospect_id) REFERENCES prospects(id);
alter table public."prospect_subject_interests" add constraint "prospect_subject_interests_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."prospect_subject_interests" add constraint "prospect_subject_interests_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id);
alter table public."prospect_subject_interests" add constraint "scope_7d8b4f6b1b91e1d4f2b683ee" FOREIGN KEY (scope_branch_id, prospect_id) REFERENCES prospects(scope_branch_id, id);
alter table public."prospect_subject_interests" add constraint "scope_8f491ea4f0206ea25ac0fb22" FOREIGN KEY (scope_branch_id, subject_id) REFERENCES subjects(scope_branch_id, id);
alter table public."prospects" add constraint "prospects_application_verified_by_fkey" FOREIGN KEY (application_verified_by) REFERENCES profiles(id);
alter table public."prospects" add constraint "prospects_area_id_fkey" FOREIGN KEY (area_id) REFERENCES areas(id);
alter table public."prospects" add constraint "prospects_assigned_to_staff_id_fkey" FOREIGN KEY (assigned_to_staff_id) REFERENCES staff(id);
alter table public."prospects" add constraint "prospects_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."prospects" add constraint "prospects_converted_student_fkey" FOREIGN KEY (converted_student_id) REFERENCES students(id);
alter table public."prospects" add constraint "prospects_current_class_id_fkey" FOREIGN KEY (current_class_id) REFERENCES classes(id);
alter table public."prospects" add constraint "prospects_guardian_relationship_id_fkey" FOREIGN KEY (guardian_relationship_id) REFERENCES guardian_relationships(id);
alter table public."prospects" add constraint "prospects_interested_offering_id_fkey" FOREIGN KEY (interested_offering_id) REFERENCES programme_offerings(id);
alter table public."prospects" add constraint "prospects_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."prospects" add constraint "prospects_school_id_fkey" FOREIGN KEY (school_id) REFERENCES schools(id);
alter table public."prospects" add constraint "prospects_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."prospects" add constraint "prospects_source_id_fkey" FOREIGN KEY (source_id) REFERENCES lead_sources(id);
alter table public."prospects" add constraint "scope_07a09f7077ce12b258061301" FOREIGN KEY (scope_branch_id, school_id) REFERENCES schools(scope_branch_id, id);
alter table public."prospects" add constraint "scope_188bb216d2eb55bded3e19bb" FOREIGN KEY (scope_branch_id, source_id) REFERENCES lead_sources(scope_branch_id, id);
alter table public."prospects" add constraint "scope_4eeb0f2a51ae6622a1b10693" FOREIGN KEY (scope_branch_id, assigned_to_staff_id) REFERENCES staff(scope_branch_id, id);
alter table public."prospects" add constraint "scope_6604227cc60c20960691f7b8" FOREIGN KEY (scope_branch_id, guardian_relationship_id) REFERENCES guardian_relationships(scope_branch_id, id);
alter table public."prospects" add constraint "scope_99552153ee2d736eb700a87d" FOREIGN KEY (scope_branch_id, area_id) REFERENCES areas(scope_branch_id, id);
alter table public."prospects" add constraint "scope_a653da59c2b8af943b3fbbba" FOREIGN KEY (scope_branch_id, current_class_id) REFERENCES classes(scope_branch_id, id);
alter table public."prospects" add constraint "scope_dfd201e2da96a4f570c691ec" FOREIGN KEY (scope_branch_id, converted_student_id) REFERENCES students(scope_branch_id, id);
alter table public."prospects" add constraint "scope_ef1363e06f09deaf9168cbfc" FOREIGN KEY (scope_branch_id, interested_offering_id) REFERENCES programme_offerings(scope_branch_id, id);
alter table public."question_bank_items" add constraint "question_bank_items_author_id_fkey" FOREIGN KEY (author_id) REFERENCES profiles(id);
alter table public."question_bank_items" add constraint "question_bank_items_batch_id_fkey" FOREIGN KEY (batch_id) REFERENCES batches(id);
alter table public."question_bank_items" add constraint "question_bank_items_curriculum_version_id_fkey" FOREIGN KEY (curriculum_version_id) REFERENCES curriculum_versions(id);
alter table public."question_bank_items" add constraint "question_bank_items_reviewer_id_fkey" FOREIGN KEY (reviewer_id) REFERENCES profiles(id);
alter table public."question_bank_items" add constraint "question_bank_items_root_id_fkey" FOREIGN KEY (root_id) REFERENCES question_bank_items(id);
alter table public."question_bank_items" add constraint "question_bank_items_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."question_bank_items" add constraint "question_bank_items_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id);
alter table public."question_bank_items" add constraint "scope_02d0e97b7e1c5f55c0c6fe22" FOREIGN KEY (scope_branch_id, curriculum_version_id) REFERENCES curriculum_versions(scope_branch_id, id);
alter table public."question_bank_items" add constraint "scope_728bdef555aff93f56ecbcdb" FOREIGN KEY (scope_branch_id, subject_id) REFERENCES subjects(scope_branch_id, id);
alter table public."question_bank_items" add constraint "scope_946b871fd2c5f17c8b6e1ea6" FOREIGN KEY (scope_branch_id, root_id) REFERENCES question_bank_items(scope_branch_id, id);
alter table public."question_bank_items" add constraint "scope_d27679e32529f449f3cffab0" FOREIGN KEY (scope_branch_id, batch_id) REFERENCES batches(scope_branch_id, id);
alter table public."role_permissions" add constraint "role_permissions_permission_id_fkey" FOREIGN KEY (permission_id) REFERENCES permissions(id);
alter table public."role_permissions" add constraint "role_permissions_role_id_fkey" FOREIGN KEY (role_id) REFERENCES system_roles(id);
alter table public."schools" add constraint "schools_area_id_fkey" FOREIGN KEY (area_id) REFERENCES areas(id);
alter table public."schools" add constraint "schools_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."schools" add constraint "schools_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."schools" add constraint "schools_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."schools" add constraint "scope_145078ab38c3e25d23f574b4" FOREIGN KEY (scope_branch_id, area_id) REFERENCES areas(scope_branch_id, id);
alter table public."staff" add constraint "staff_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."staff" add constraint "staff_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."staff" add constraint "staff_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id);
alter table public."staff" add constraint "staff_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."staff_access_requests" add constraint "staff_access_requests_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id);
alter table public."staff_access_requests" add constraint "staff_access_requests_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES profiles(id);
alter table public."staff_access_requests" add constraint "staff_access_requests_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."staff_admission_intake_requests" add constraint "scope_258b7df20f20996cd758ceae" FOREIGN KEY (scope_branch_id, prospect_id) REFERENCES prospects(scope_branch_id, id);
alter table public."staff_admission_intake_requests" add constraint "scope_2a18a93da19c3224e8195f29" FOREIGN KEY (scope_branch_id, admission_id) REFERENCES admission_cases(scope_branch_id, id);
alter table public."staff_admission_intake_requests" add constraint "staff_admission_intake_requests_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES profiles(id);
alter table public."staff_admission_intake_requests" add constraint "staff_admission_intake_requests_admission_id_fkey" FOREIGN KEY (admission_id) REFERENCES admission_cases(id);
alter table public."staff_admission_intake_requests" add constraint "staff_admission_intake_requests_prospect_id_fkey" FOREIGN KEY (prospect_id) REFERENCES prospects(id);
alter table public."staff_admission_intake_requests" add constraint "staff_admission_intake_requests_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."staff_attendance_records" add constraint "scope_81e8a4aabc5e200a1ad69946" FOREIGN KEY (scope_branch_id, staff_id) REFERENCES staff(scope_branch_id, id);
alter table public."staff_attendance_records" add constraint "staff_attendance_records_recorded_by_fkey" FOREIGN KEY (recorded_by) REFERENCES profiles(id);
alter table public."staff_attendance_records" add constraint "staff_attendance_records_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."staff_attendance_records" add constraint "staff_attendance_records_staff_id_fkey" FOREIGN KEY (staff_id) REFERENCES staff(id);
alter table public."staff_role_assignments" add constraint "scope_00e12a8ab02557355c0f2254" FOREIGN KEY (scope_branch_id, staff_id) REFERENCES staff(scope_branch_id, id);
alter table public."staff_role_assignments" add constraint "staff_role_assignments_assigned_by_fkey" FOREIGN KEY (assigned_by) REFERENCES profiles(id);
alter table public."staff_role_assignments" add constraint "staff_role_assignments_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."staff_role_assignments" add constraint "staff_role_assignments_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."staff_role_assignments" add constraint "staff_role_assignments_staff_id_fkey" FOREIGN KEY (staff_id) REFERENCES staff(id);
alter table public."staff_role_assignments" add constraint "staff_role_assignments_staff_role_id_fkey" FOREIGN KEY (staff_role_id) REFERENCES staff_roles(id);
alter table public."staff_subject_assignments" add constraint "scope_0b683b721b4e5ad1499d41a5" FOREIGN KEY (scope_branch_id, subject_id) REFERENCES subjects(scope_branch_id, id);
alter table public."staff_subject_assignments" add constraint "scope_7e23ddd2d8eca2f69b1b6659" FOREIGN KEY (scope_branch_id, staff_id) REFERENCES staff(scope_branch_id, id);
alter table public."staff_subject_assignments" add constraint "staff_subject_assignments_assigned_by_fkey" FOREIGN KEY (assigned_by) REFERENCES profiles(id);
alter table public."staff_subject_assignments" add constraint "staff_subject_assignments_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."staff_subject_assignments" add constraint "staff_subject_assignments_staff_id_fkey" FOREIGN KEY (staff_id) REFERENCES staff(id);
alter table public."staff_subject_assignments" add constraint "staff_subject_assignments_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id);
alter table public."staff_work_tasks" add constraint "scope_41769495e301c36e148553dd" FOREIGN KEY (scope_branch_id, staff_id) REFERENCES staff(scope_branch_id, id);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_staff_id_fkey" FOREIGN KEY (staff_id) REFERENCES staff(id);
alter table public."staff_work_tasks" add constraint "staff_work_tasks_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id);
alter table public."student_guardians" add constraint "scope_340f04575cb478cc678fa932" FOREIGN KEY (scope_branch_id, guardian_id) REFERENCES guardians(scope_branch_id, id);
alter table public."student_guardians" add constraint "scope_793510d3d2e5e65c5a20f1a6" FOREIGN KEY (scope_branch_id, relationship_id) REFERENCES guardian_relationships(scope_branch_id, id);
alter table public."student_guardians" add constraint "scope_8bbec63538b0a19dbf0562bb" FOREIGN KEY (scope_branch_id, student_id) REFERENCES students(scope_branch_id, id);
alter table public."student_guardians" add constraint "student_guardians_guardian_id_fkey" FOREIGN KEY (guardian_id) REFERENCES guardians(id);
alter table public."student_guardians" add constraint "student_guardians_relationship_id_fkey" FOREIGN KEY (relationship_id) REFERENCES guardian_relationships(id);
alter table public."student_guardians" add constraint "student_guardians_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."student_guardians" add constraint "student_guardians_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id);
alter table public."student_merges" add constraint "scope_148db9ae81b98f336b4288cc" FOREIGN KEY (scope_branch_id, target_id) REFERENCES students(scope_branch_id, id);
alter table public."student_merges" add constraint "scope_fa1de3248095b875164de933" FOREIGN KEY (scope_branch_id, source_id) REFERENCES students(scope_branch_id, id);
alter table public."student_merges" add constraint "student_merges_authorized_by_fkey" FOREIGN KEY (authorized_by) REFERENCES profiles(id);
alter table public."student_merges" add constraint "student_merges_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."student_merges" add constraint "student_merges_source_id_fkey" FOREIGN KEY (source_id) REFERENCES students(id);
alter table public."student_merges" add constraint "student_merges_target_id_fkey" FOREIGN KEY (target_id) REFERENCES students(id);
alter table public."students" add constraint "scope_2e366f1885e30a1fb753022b" FOREIGN KEY (scope_branch_id, merged_into_id) REFERENCES students(scope_branch_id, id);
alter table public."students" add constraint "scope_3db645a4dbb4224acd25d8cc" FOREIGN KEY (scope_branch_id, created_from_prospect_id) REFERENCES prospects(scope_branch_id, id);
alter table public."students" add constraint "scope_5143e54f14534fa42f73ff5b" FOREIGN KEY (scope_branch_id, school_id) REFERENCES schools(scope_branch_id, id);
alter table public."students" add constraint "students_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."students" add constraint "students_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."students" add constraint "students_created_from_prospect_id_fkey" FOREIGN KEY (created_from_prospect_id) REFERENCES prospects(id);
alter table public."students" add constraint "students_merged_into_id_fkey" FOREIGN KEY (merged_into_id) REFERENCES students(id);
alter table public."students" add constraint "students_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."students" add constraint "students_school_id_fkey" FOREIGN KEY (school_id) REFERENCES schools(id);
alter table public."students" add constraint "students_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."subjects" add constraint "subjects_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id);
alter table public."subjects" add constraint "subjects_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
alter table public."user_role_assignments" add constraint "user_role_assignments_assigned_by_fkey" FOREIGN KEY (assigned_by) REFERENCES profiles(id);
alter table public."user_role_assignments" add constraint "user_role_assignments_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id);
alter table public."user_role_assignments" add constraint "user_role_assignments_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id);
alter table public."user_role_assignments" add constraint "user_role_assignments_role_id_fkey" FOREIGN KEY (role_id) REFERENCES system_roles(id);
alter table public."user_role_assignments" add constraint "user_role_assignments_scope_branch_id_fkey" FOREIGN KEY (scope_branch_id) REFERENCES branches(id);
CREATE INDEX academic_assessments_scope ON public.academic_assessments USING btree (batch_id, subject_id, assessment_date DESC);
CREATE INDEX admission_cases_consent_gate_idx ON public.admission_cases USING btree (consent_required, status);
CREATE INDEX admission_cases_origin_idx ON public.admission_cases USING btree (origin, created_at DESC);
CREATE UNIQUE INDEX admission_open_prospect ON public.admission_cases USING btree (prospect_id) WHERE (status <> 'CANCELLED'::text);
CREATE INDEX admission_physical_consent_case_idx ON public.admission_physical_consent_receipts USING btree (admission_id, version DESC);
CREATE INDEX admission_student_history ON public.admission_cases USING btree (student_id, created_at);
CREATE INDEX approval_requests_pending_idx ON public.approval_requests USING btree (status, requested_at) WHERE (status = 'PENDING'::approval_status);
CREATE UNIQUE INDEX areas_name_parent_uniq ON public.areas USING btree (scope_branch_id, organization_id, lower(name), COALESCE(parent_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE UNIQUE INDEX assessment_one_draft ON public.assessment_result_submissions USING btree (assessment_id) WHERE (status = 'DRAFT'::text);
CREATE UNIQUE INDEX assessment_one_pending ON public.assessment_result_submissions USING btree (assessment_id) WHERE (status = 'SUBMITTED'::text);
CREATE INDEX attendance_reviewed_idx ON public.attendance_submissions USING btree (session_id, status, revision DESC);
CREATE INDEX audit_events_correlation_idx ON public.audit_events USING btree (correlation_id);
CREATE INDEX audit_events_entity_action_time ON public.audit_events USING btree (entity_type, action, occurred_at DESC, id DESC);
CREATE INDEX audit_events_entity_idx ON public.audit_events USING btree (entity_type, entity_id, occurred_at DESC);
CREATE INDEX audit_events_time_id ON public.audit_events USING btree (occurred_at DESC, id DESC);
CREATE UNIQUE INDEX class_logs_one_pending_per_session ON public.class_logs USING btree (session_id) WHERE (status = 'SUBMITTED'::text);
CREATE INDEX class_logs_session_history ON public.class_logs USING btree (session_id, revision DESC);
CREATE INDEX guardians_mobile_idx ON public.guardians USING btree (regexp_replace(mobile, '\D'::text, ''::text, 'g'::text));
CREATE INDEX homework_checks_history ON public.homework_checks USING btree (class_log_id, enrollment_id, revision DESC);
CREATE UNIQUE INDEX one_active_business_rule ON public.business_rule_versions USING btree (scope_branch_id, domain, rule_key) WHERE (status = 'ACTIVE'::rule_status);
CREATE UNIQUE INDEX one_active_enrollment_per_student_year ON public.enrollments USING btree (student_id, academic_year_id) WHERE (status = 'ACTIVE'::enrollment_status);
CREATE UNIQUE INDEX one_class_log_draft_per_session ON public.class_logs USING btree (session_id) WHERE (status = 'DRAFT'::text);
CREATE UNIQUE INDEX one_pending_attendance ON public.attendance_submissions USING btree (session_id) WHERE (status = 'SUBMITTED'::text);
CREATE UNIQUE INDEX one_primary_guardian_per_student ON public.student_guardians USING btree (student_id) WHERE is_primary;
CREATE UNIQUE INDEX programme_offering_context_uniq ON public.programme_offerings USING btree (academic_year_id, branch_id, class_id, program_id, COALESCE(group_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX programme_offerings_website_visible_idx ON public.programme_offerings USING btree (showcase_sort_order, created_at) WHERE ((is_website_visible = true) AND (status = 'ACTIVE'::offering_status));
CREATE INDEX prospects_followup_idx ON public.prospects USING btree (next_follow_up_at) WHERE (next_follow_up_at IS NOT NULL);
CREATE INDEX prospects_interested_offering_idx ON public.prospects USING btree (interested_offering_id) WHERE (interested_offering_id IS NOT NULL);
CREATE INDEX prospects_mobile_idx ON public.prospects USING btree (regexp_replace(mobile, '\D'::text, ''::text, 'g'::text));
CREATE INDEX prospects_status_idx ON public.prospects USING btree (status, created_at DESC);
CREATE UNIQUE INDEX question_bank_one_draft ON public.question_bank_items USING btree (COALESCE(root_id, id)) WHERE (status = 'DRAFT'::text);
CREATE INDEX question_bank_scope_idx ON public.question_bank_items USING btree (batch_id, subject_id, created_at DESC);
CREATE INDEX schools_search_idx ON public.schools USING btree (lower(name));
CREATE INDEX sessions_schedule ON public.class_sessions USING btree (starts_at, ends_at) WHERE (status = 'SCHEDULED'::text);
CREATE UNIQUE INDEX staff_access_open_email ON public.staff_access_requests USING btree (scope_branch_id, lower(email)) WHERE (status = ANY (ARRAY['PENDING'::text, 'VERIFIED'::text, 'INVITED'::text]));
CREATE INDEX staff_attendance_date_idx ON public.staff_attendance_records USING btree (work_date, staff_id);
CREATE UNIQUE INDEX staff_primary_open_role_uniq ON public.staff_role_assignments USING btree (staff_id) WHERE (is_primary AND (effective_to IS NULL));
CREATE UNIQUE INDEX staff_subject_open_assignment_uniq ON public.staff_subject_assignments USING btree (staff_id, subject_id) WHERE (effective_to IS NULL);
CREATE UNIQUE INDEX student_academy_roll_unique ON public.students USING btree (academy_roll);
CREATE INDEX students_merged_into ON public.students USING btree (merged_into_id) WHERE (merged_into_id IS NOT NULL);
CREATE UNIQUE INDEX user_role_open_assignment_uniq ON public.user_role_assignments USING btree (profile_id, role_id, COALESCE(branch_id, '00000000-0000-0000-0000-000000000000'::uuid)) WHERE (is_active AND (effective_to IS NULL));
CREATE INDEX work_task_queue_idx ON public.staff_work_tasks USING btree (staff_id, status, due_on, id);
