-- Explicit stable function ownership and restricted API access.
do $$ begin if not exists(select 1 from pg_roles where rolname='academy_executor') then create role academy_executor nologin nobypassrls;end if;end $$;
do $$ begin execute format('grant academy_executor to %I',current_user);
 end $$;
-- Hosted Supabase may pre-grant newly created public tables to API roles.
-- Start from deny-by-default, then restore only the reviewed grants below.
revoke all on all tables in schema public from anon,authenticated;
revoke all on all sequences in schema public from anon,authenticated;
do $$ declare item record;begin
 for item in select c.relname,c.relkind from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in('r','v','S') loop
  execute format('alter %s public.%I owner to postgres',case item.relkind when 'S' then 'sequence' when 'v' then 'view' else 'table' end,item.relname);
 end loop;
end $$;
alter schema academy_private owner to postgres;
grant usage on schema public,academy_private,auth to academy_executor;
grant create on schema public to academy_executor;
grant usage on schema auth to postgres;
grant select on auth.users to postgres,academy_executor;
grant execute on function auth.uid() to postgres,academy_executor;
revoke all on schema academy_private from public,anon,authenticated;
grant usage on schema academy_private to authenticated;
grant usage on schema public to anon,authenticated;
grant all on all tables in schema public to academy_executor;
grant usage,select on all sequences in schema public to academy_executor;
alter table public."academic_assessments" enable row level security;
alter table public."academic_assessments" force row level security;
create policy "branch_scope" on public."academic_assessments" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."academic_assessments" as permissive for all to academy_executor using (true) with check (true);
alter table public."academic_groups" enable row level security;
alter table public."academic_groups" force row level security;
create policy "academic_groups_read" on public."academic_groups" as permissive for select to authenticated using ((has_permission('academics.view'::text) OR has_permission('admissions.view'::text)));
create policy "branch_scope" on public."academic_groups" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."academic_groups" as permissive for all to academy_executor using (true) with check (true);
create policy "master_data_manage_academic_groups" on public."academic_groups" as permissive for all to authenticated using (has_permission('system.master_data.manage'::text)) with check (has_permission('system.master_data.manage'::text));
grant SELECT on public."academic_groups" to authenticated;
alter table public."academic_rooms" enable row level security;
alter table public."academic_rooms" force row level security;
create policy "academic_room_read" on public."academic_rooms" as permissive for select to authenticated using (has_permission('academics.view'::text));
create policy "branch_scope" on public."academic_rooms" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."academic_rooms" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."academic_rooms" to authenticated;
alter table public."academic_routines" enable row level security;
alter table public."academic_routines" force row level security;
create policy "branch_scope" on public."academic_routines" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."academic_routines" as permissive for all to academy_executor using (true) with check (true);
create policy "routine_read" on public."academic_routines" as permissive for select to authenticated using ((has_permission('academics.sessions.manage'::text) OR (EXISTS ( SELECT 1
   FROM staff
  WHERE ((staff.id = academic_routines.teacher_id) AND (staff.profile_id = auth.uid()))))));
grant SELECT on public."academic_routines" to authenticated;
alter table public."academic_years" enable row level security;
alter table public."academic_years" force row level security;
create policy "academic_years_read" on public."academic_years" as permissive for select to authenticated using (true);
create policy "branch_scope" on public."academic_years" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."academic_years" as permissive for all to academy_executor using (true) with check (true);
create policy "master_data_manage_academic_years" on public."academic_years" as permissive for all to authenticated using (has_permission('system.master_data.manage'::text)) with check (has_permission('system.master_data.manage'::text));
grant SELECT on public."academic_years" to authenticated;
alter table public."admission_cases" enable row level security;
alter table public."admission_cases" force row level security;
create policy "admission_cases_read" on public."admission_cases" as permissive for select to authenticated using (has_permission('admissions.view'::text));
create policy "branch_scope" on public."admission_cases" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."admission_cases" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."admission_cases" to authenticated;
alter table public."admission_command_keys" enable row level security;
alter table public."admission_command_keys" force row level security;
create policy "branch_scope" on public."admission_command_keys" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."admission_command_keys" as permissive for all to academy_executor using (true) with check (true);
alter table public."admission_physical_consent_receipts" enable row level security;
alter table public."admission_physical_consent_receipts" force row level security;
create policy "admission_physical_consent_staff_read" on public."admission_physical_consent_receipts" as permissive for select to authenticated using (has_permission('admissions.view'::text));
create policy "branch_scope" on public."admission_physical_consent_receipts" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."admission_physical_consent_receipts" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."admission_physical_consent_receipts" to authenticated;
alter table public."approval_requests" enable row level security;
alter table public."approval_requests" force row level security;
create policy "approvals_decide" on public."approval_requests" as permissive for update to authenticated using (has_permission('approvals.decide'::text)) with check (has_permission('approvals.decide'::text));
create policy "approvals_permission_read" on public."approval_requests" as permissive for select to authenticated using ((has_permission('approvals.view'::text) OR (requested_by = auth.uid())));
create policy "approvals_submit" on public."approval_requests" as permissive for insert to authenticated with check ((requested_by = auth.uid()));
create policy "branch_scope" on public."approval_requests" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."approval_requests" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."approval_requests" to authenticated;
alter table public."areas" enable row level security;
alter table public."areas" force row level security;
create policy "areas_authenticated_read" on public."areas" as permissive for select to authenticated using (is_active);
create policy "branch_scope" on public."areas" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."areas" as permissive for all to academy_executor using (true) with check (true);
create policy "master_data_manage_areas" on public."areas" as permissive for all to authenticated using (has_permission('system.master_data.manage'::text)) with check (has_permission('system.master_data.manage'::text));
grant SELECT on public."areas" to authenticated;
alter table public."assessment_result_submissions" enable row level security;
alter table public."assessment_result_submissions" force row level security;
create policy "branch_scope" on public."assessment_result_submissions" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."assessment_result_submissions" as permissive for all to academy_executor using (true) with check (true);
alter table public."attendance_submissions" enable row level security;
alter table public."attendance_submissions" force row level security;
create policy "attendance_read" on public."attendance_submissions" as permissive for select to authenticated using (can_access_class_session(session_id));
create policy "branch_scope" on public."attendance_submissions" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."attendance_submissions" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."attendance_submissions" to authenticated;
alter table public."audit_events" enable row level security;
alter table public."audit_events" force row level security;
create policy "audit_permission_read" on public."audit_events" as permissive for select to authenticated using (has_permission('audit.view'::text));
create policy "branch_scope" on public."audit_events" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."audit_events" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."audit_events" to authenticated;
alter table public."batches" enable row level security;
alter table public."batches" force row level security;
create policy "batches_manage" on public."batches" as permissive for all to authenticated using (has_permission('academics.manage'::text)) with check (has_permission('academics.manage'::text));
create policy "batches_view" on public."batches" as permissive for select to authenticated using ((has_permission('academics.view'::text) OR has_permission('admissions.view'::text)));
create policy "branch_scope" on public."batches" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."batches" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."batches" to authenticated;
alter table public."branch_memberships" enable row level security;
create policy "own_memberships" on public."branch_memberships" as permissive for select to authenticated,academy_executor using ((user_id = auth.uid()));
grant SELECT on public."branch_memberships" to authenticated;
alter table public."branch_open_commands" enable row level security;
alter table public."branch_owners" enable row level security;
alter table public."branches" enable row level security;
alter table public."branches" force row level security;
create policy "branch_registry_scope" on public."branches" as restrictive for all to authenticated,academy_executor using ((id = academy_private.current_branch_id())) with check ((id = academy_private.current_branch_id()));
create policy "branches_authenticated_read" on public."branches" as permissive for select to authenticated using (true);
create policy "executor_workflows" on public."branches" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."branches" to authenticated;
alter table public."business_rule_versions" enable row level security;
alter table public."business_rule_versions" force row level security;
create policy "branch_scope" on public."business_rule_versions" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "business_rules_read" on public."business_rule_versions" as permissive for select to authenticated using ((has_permission('system.rules.view'::text) OR (status = 'ACTIVE'::rule_status)));
create policy "executor_workflows" on public."business_rule_versions" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."business_rule_versions" to authenticated;
alter table public."class_logs" enable row level security;
alter table public."class_logs" force row level security;
create policy "branch_scope" on public."class_logs" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."class_logs" as permissive for all to academy_executor using (true) with check (true);
alter table public."class_sessions" enable row level security;
alter table public."class_sessions" force row level security;
create policy "branch_scope" on public."class_sessions" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."class_sessions" as permissive for all to academy_executor using (true) with check (true);
create policy "session_read" on public."class_sessions" as permissive for select to authenticated using (can_access_class_session(id));
grant SELECT on public."class_sessions" to authenticated;
alter table public."classes" enable row level security;
alter table public."classes" force row level security;
create policy "branch_scope" on public."classes" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "classes_public_read" on public."classes" as permissive for select to anon,authenticated using (is_active);
create policy "executor_workflows" on public."classes" as permissive for all to academy_executor using (true) with check (true);
create policy "master_data_manage_classes" on public."classes" as permissive for all to authenticated using (has_permission('system.master_data.manage'::text)) with check (has_permission('system.master_data.manage'::text));
grant SELECT on public."classes" to authenticated;
alter table public."curriculum_versions" enable row level security;
alter table public."curriculum_versions" force row level security;
create policy "branch_scope" on public."curriculum_versions" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "curriculum_read" on public."curriculum_versions" as permissive for select to authenticated using ((has_permission('academics.curriculum.manage'::text) OR has_permission('academics.sessions.manage'::text) OR (EXISTS ( SELECT 1
   FROM class_sessions s
  WHERE ((s.curriculum_version_id = curriculum_versions.id) AND can_access_class_session(s.id))))));
create policy "executor_workflows" on public."curriculum_versions" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."curriculum_versions" to authenticated;
alter table public."enrollment_transfers" enable row level security;
alter table public."enrollment_transfers" force row level security;
create policy "branch_scope" on public."enrollment_transfers" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."enrollment_transfers" as permissive for all to academy_executor using (true) with check (true);
create policy "lifecycle_read" on public."enrollment_transfers" as permissive for select to authenticated using (has_permission('students.view'::text));
grant SELECT on public."enrollment_transfers" to authenticated;
alter table public."enrollments" enable row level security;
alter table public."enrollments" force row level security;
create policy "branch_scope" on public."enrollments" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "enrollments_manage" on public."enrollments" as permissive for all to authenticated using ((has_permission('students.manage'::text) OR has_permission('admissions.create'::text))) with check ((has_permission('students.manage'::text) OR has_permission('admissions.create'::text)));
create policy "enrollments_view" on public."enrollments" as permissive for select to authenticated using ((has_permission('students.view'::text) OR has_permission('admissions.view'::text)));
create policy "executor_workflows" on public."enrollments" as permissive for all to academy_executor using (true) with check (true);
grant SELECT on public."enrollments" to authenticated;
alter table public."guardian_relationships" enable row level security;
alter table public."guardian_relationships" force row level security;
create policy "branch_scope" on public."guardian_relationships" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."guardian_relationships" as permissive for all to academy_executor using (true) with check (true);
create policy "guardian_relationships_authenticated_read" on public."guardian_relationships" as permissive for select to authenticated using (is_active);
create policy "guardian_relationships_public_read" on public."guardian_relationships" as permissive for select to anon using (is_active);
create policy "master_data_manage_guardian_relationships" on public."guardian_relationships" as permissive for all to authenticated using (has_permission('system.master_data.manage'::text)) with check (has_permission('system.master_data.manage'::text));
grant SELECT on public."guardian_relationships" to authenticated;
alter table public."guardians" enable row level security;
alter table public."guardians" force row level security;
create policy "branch_scope" on public."guardians" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."guardians" as permissive for all to academy_executor using (true) with check (true);
create policy "guardians_manage" on public."guardians" as permissive for all to authenticated using (has_permission('students.manage'::text)) with check (has_permission('students.manage'::text));
create policy "guardians_view" on public."guardians" as permissive for select to authenticated using (has_permission('students.view'::text));
grant SELECT on public."guardians" to authenticated;
alter table public."homework_checks" enable row level security;
alter table public."homework_checks" force row level security;
create policy "branch_scope" on public."homework_checks" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."homework_checks" as permissive for all to academy_executor using (true) with check (true);
alter table public."lead_sources" enable row level security;
alter table public."lead_sources" force row level security;
create policy "branch_scope" on public."lead_sources" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."lead_sources" as permissive for all to academy_executor using (true) with check (true);
create policy "lead_sources_public_read" on public."lead_sources" as permissive for select to anon,authenticated using (is_active);
create policy "master_data_manage_lead_sources" on public."lead_sources" as permissive for all to authenticated using (has_permission('system.master_data.manage'::text)) with check (has_permission('system.master_data.manage'::text));
grant SELECT on public."lead_sources" to authenticated;
alter table public."organizations" enable row level security;
alter table public."organizations" force row level security;
create policy "executor_workflows" on public."organizations" as permissive for all to academy_executor using (true) with check (true);
create policy "organization_scope" on public."organizations" as restrictive for all to authenticated,academy_executor using ((id = ( SELECT branches.organization_id
   FROM branches
  WHERE (branches.id = academy_private.current_branch_id())))) with check ((id = ( SELECT branches.organization_id
   FROM branches
  WHERE (branches.id = academy_private.current_branch_id()))));
create policy "organizations_authenticated_read" on public."organizations" as permissive for select to authenticated using (true);
grant SELECT on public."organizations" to authenticated;
alter table public."permissions" enable row level security;
create policy "executor_catalogue_read" on public."permissions" as permissive for select to academy_executor using ((academy_private.current_branch_id() IS NOT NULL));
create policy "permissions_read" on public."permissions" as permissive for select to authenticated using (true);
grant SELECT on public."permissions" to authenticated;
alter table public."profiles" enable row level security;
alter table public."profiles" force row level security;
create policy "executor_workflows" on public."profiles" as permissive for all to academy_executor using (true) with check (true);
create policy "profile_scope" on public."profiles" as restrictive for all to authenticated,academy_executor using (((id = auth.uid()) OR academy_private.is_branch_member(id))) with check (((id = auth.uid()) OR academy_private.is_branch_member(id)));
create policy "profiles_read" on public."profiles" as permissive for select to authenticated using (((id = auth.uid()) OR has_permission('system.users.manage'::text) OR has_permission('staff.view'::text)));
grant SELECT on public."profiles" to authenticated;
alter table public."programme_offering_subjects" enable row level security;
alter table public."programme_offering_subjects" force row level security;
create policy "branch_scope" on public."programme_offering_subjects" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."programme_offering_subjects" as permissive for all to academy_executor using (true) with check (true);
create policy "offering_subjects_read" on public."programme_offering_subjects" as permissive for select to anon,authenticated using ((EXISTS ( SELECT 1
   FROM programme_offerings o
  WHERE ((o.id = programme_offering_subjects.offering_id) AND (o.is_website_visible OR has_permission('academics.view'::text) OR has_permission('admissions.view'::text))))));
grant SELECT on public."programme_offering_subjects" to authenticated;
alter table public."programme_offerings" enable row level security;
alter table public."programme_offerings" force row level security;
create policy "branch_scope" on public."programme_offerings" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."programme_offerings" as permissive for all to academy_executor using (true) with check (true);
create policy "programme_offerings_read" on public."programme_offerings" as permissive for select to authenticated using ((has_permission('academics.view'::text) OR has_permission('admissions.view'::text) OR has_permission('finance.view'::text)));
grant SELECT on public."programme_offerings" to authenticated;
alter table public."programs" enable row level security;
alter table public."programs" force row level security;
create policy "branch_scope" on public."programs" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."programs" as permissive for all to academy_executor using (true) with check (true);
create policy "master_data_manage_programs" on public."programs" as permissive for all to authenticated using (has_permission('system.master_data.manage'::text)) with check (has_permission('system.master_data.manage'::text));
create policy "programs_public_read" on public."programs" as permissive for select to anon,authenticated using (is_active);
grant SELECT on public."programs" to authenticated;
alter table public."prospect_followups" enable row level security;
alter table public."prospect_followups" force row level security;
create policy "branch_scope" on public."prospect_followups" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."prospect_followups" as permissive for all to academy_executor using (true) with check (true);
create policy "prospect_followups_manage" on public."prospect_followups" as permissive for all to authenticated using (has_permission('crm.followups.manage'::text)) with check ((has_permission('crm.followups.manage'::text) AND (recorded_by = auth.uid())));
create policy "prospect_followups_view" on public."prospect_followups" as permissive for select to authenticated using (has_permission('crm.prospects.view'::text));
grant SELECT on public."prospect_followups" to authenticated;
alter table public."prospect_program_interests" enable row level security;
alter table public."prospect_program_interests" force row level security;
create policy "branch_scope" on public."prospect_program_interests" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."prospect_program_interests" as permissive for all to academy_executor using (true) with check (true);
create policy "prospect_program_interests_manage" on public."prospect_program_interests" as permissive for all to authenticated using (has_permission('crm.prospects.manage'::text)) with check (has_permission('crm.prospects.manage'::text));
create policy "prospect_program_interests_view" on public."prospect_program_interests" as permissive for select to authenticated using (has_permission('crm.prospects.view'::text));
grant SELECT on public."prospect_program_interests" to authenticated;
alter table public."prospect_subject_interests" enable row level security;
alter table public."prospect_subject_interests" force row level security;
create policy "branch_scope" on public."prospect_subject_interests" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."prospect_subject_interests" as permissive for all to academy_executor using (true) with check (true);
create policy "prospect_subject_interests_manage" on public."prospect_subject_interests" as permissive for all to authenticated using (has_permission('crm.prospects.manage'::text)) with check (has_permission('crm.prospects.manage'::text));
create policy "prospect_subject_interests_view" on public."prospect_subject_interests" as permissive for select to authenticated using (has_permission('crm.prospects.view'::text));
grant SELECT on public."prospect_subject_interests" to authenticated;
alter table public."prospects" enable row level security;
alter table public."prospects" force row level security;
create policy "branch_scope" on public."prospects" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."prospects" as permissive for all to academy_executor using (true) with check (true);
create policy "prospects_manage_insert" on public."prospects" as permissive for insert to authenticated with check (has_permission('crm.prospects.manage'::text));
create policy "prospects_manage_update" on public."prospects" as permissive for update to authenticated using (has_permission('crm.prospects.manage'::text)) with check (has_permission('crm.prospects.manage'::text));
create policy "prospects_view" on public."prospects" as permissive for select to authenticated using (has_permission('crm.prospects.view'::text));
grant SELECT on public."prospects" to authenticated;
alter table public."question_bank_items" enable row level security;
alter table public."question_bank_items" force row level security;
create policy "branch_scope" on public."question_bank_items" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."question_bank_items" as permissive for all to academy_executor using (true) with check (true);
alter table public."role_permissions" enable row level security;
create policy "executor_catalogue_read" on public."role_permissions" as permissive for select to academy_executor using ((academy_private.current_branch_id() IS NOT NULL));
create policy "role_permissions_read" on public."role_permissions" as permissive for select to authenticated using ((has_permission('system.roles.manage'::text) OR has_permission('system.users.manage'::text)));
grant SELECT on public."role_permissions" to authenticated;
alter table public."schools" enable row level security;
alter table public."schools" force row level security;
create policy "branch_scope" on public."schools" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."schools" as permissive for all to academy_executor using (true) with check (true);
create policy "master_data_manage_schools" on public."schools" as permissive for all to authenticated using (has_permission('system.master_data.manage'::text)) with check (has_permission('system.master_data.manage'::text));
create policy "schools_public_read" on public."schools" as permissive for select to anon,authenticated using (is_active);
grant SELECT on public."schools" to authenticated;
alter table public."staff" enable row level security;
alter table public."staff" force row level security;
create policy "branch_scope" on public."staff" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."staff" as permissive for all to academy_executor using (true) with check (true);
create policy "staff_permission_insert" on public."staff" as permissive for insert to authenticated with check (has_permission('staff.manage'::text));
create policy "staff_permission_read" on public."staff" as permissive for select to authenticated using ((has_permission('staff.view'::text) OR (profile_id = auth.uid())));
create policy "staff_permission_update" on public."staff" as permissive for update to authenticated using (has_permission('staff.manage'::text)) with check (has_permission('staff.manage'::text));
grant SELECT on public."staff" to authenticated;
alter table public."staff_access_requests" enable row level security;
alter table public."staff_access_requests" force row level security;
create policy "branch_scope" on public."staff_access_requests" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."staff_access_requests" as permissive for all to academy_executor using (true) with check (true);
create policy "staff_requests_read" on public."staff_access_requests" as permissive for select to authenticated using (has_permission('system.users.manage'::text));
grant SELECT on public."staff_access_requests" to authenticated;
alter table public."staff_admission_intake_requests" enable row level security;
alter table public."staff_admission_intake_requests" force row level security;
create policy "branch_scope" on public."staff_admission_intake_requests" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."staff_admission_intake_requests" as permissive for all to academy_executor using (true) with check (true);
alter table public."staff_attendance_records" enable row level security;
alter table public."staff_attendance_records" force row level security;
create policy "branch_scope" on public."staff_attendance_records" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."staff_attendance_records" as permissive for all to academy_executor using (true) with check (true);
create policy "staff_attendance_scope" on public."staff_attendance_records" as permissive for select to authenticated using ((has_permission('workforce.manage'::text) OR (has_permission('workforce.self.view'::text) AND (staff_id IN ( SELECT staff.id
   FROM staff
  WHERE ((staff.profile_id = auth.uid()) AND (staff.status = 'ACTIVE'::staff_status)))))));
grant SELECT on public."staff_attendance_records" to authenticated;
alter table public."staff_role_assignments" enable row level security;
alter table public."staff_role_assignments" force row level security;
create policy "branch_scope" on public."staff_role_assignments" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."staff_role_assignments" as permissive for all to academy_executor using (true) with check (true);
create policy "staff_role_assignments_insert" on public."staff_role_assignments" as permissive for insert to authenticated with check (has_permission('staff.manage'::text));
create policy "staff_role_assignments_read" on public."staff_role_assignments" as permissive for select to authenticated using (has_permission('staff.view'::text));
create policy "staff_role_assignments_update" on public."staff_role_assignments" as permissive for update to authenticated using (has_permission('staff.manage'::text)) with check (has_permission('staff.manage'::text));
grant SELECT on public."staff_role_assignments" to authenticated;
alter table public."staff_roles" enable row level security;
create policy "executor_catalogue_read" on public."staff_roles" as permissive for select to academy_executor using ((academy_private.current_branch_id() IS NOT NULL));
create policy "staff_roles_authenticated_read" on public."staff_roles" as permissive for select to authenticated using (true);
grant SELECT on public."staff_roles" to authenticated;
alter table public."staff_subject_assignments" enable row level security;
alter table public."staff_subject_assignments" force row level security;
create policy "branch_scope" on public."staff_subject_assignments" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."staff_subject_assignments" as permissive for all to academy_executor using (true) with check (true);
create policy "staff_subjects_manage_insert" on public."staff_subject_assignments" as permissive for insert to authenticated with check (has_permission('staff.manage'::text));
create policy "staff_subjects_manage_update" on public."staff_subject_assignments" as permissive for update to authenticated using (has_permission('staff.manage'::text)) with check (has_permission('staff.manage'::text));
create policy "staff_subjects_read" on public."staff_subject_assignments" as permissive for select to authenticated using (has_permission('staff.view'::text));
grant SELECT on public."staff_subject_assignments" to authenticated;
alter table public."staff_work_tasks" enable row level security;
alter table public."staff_work_tasks" force row level security;
create policy "branch_scope" on public."staff_work_tasks" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."staff_work_tasks" as permissive for all to academy_executor using (true) with check (true);
create policy "staff_work_tasks_scope" on public."staff_work_tasks" as permissive for select to authenticated using ((has_permission('workforce.manage'::text) OR (has_permission('workforce.self.view'::text) AND (staff_id IN ( SELECT staff.id
   FROM staff
  WHERE ((staff.profile_id = auth.uid()) AND (staff.status = 'ACTIVE'::staff_status)))))));
grant SELECT on public."staff_work_tasks" to authenticated;
alter table public."student_guardians" enable row level security;
alter table public."student_guardians" force row level security;
create policy "branch_scope" on public."student_guardians" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."student_guardians" as permissive for all to academy_executor using (true) with check (true);
create policy "student_guardians_manage" on public."student_guardians" as permissive for all to authenticated using (has_permission('students.manage'::text)) with check (has_permission('students.manage'::text));
create policy "student_guardians_view" on public."student_guardians" as permissive for select to authenticated using (has_permission('students.view'::text));
grant SELECT on public."student_guardians" to authenticated;
alter table public."student_merges" enable row level security;
alter table public."student_merges" force row level security;
create policy "branch_scope" on public."student_merges" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."student_merges" as permissive for all to academy_executor using (true) with check (true);
create policy "lifecycle_read" on public."student_merges" as permissive for select to authenticated using (has_permission('students.view'::text));
grant SELECT on public."student_merges" to authenticated;
alter table public."students" enable row level security;
alter table public."students" force row level security;
create policy "branch_scope" on public."students" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."students" as permissive for all to academy_executor using (true) with check (true);
create policy "students_manage_insert" on public."students" as permissive for insert to authenticated with check (has_permission('students.manage'::text));
create policy "students_manage_update" on public."students" as permissive for update to authenticated using (has_permission('students.manage'::text)) with check (has_permission('students.manage'::text));
create policy "students_view" on public."students" as permissive for select to authenticated using (has_permission('students.view'::text));
grant SELECT on public."students" to authenticated;
alter table public."subjects" enable row level security;
alter table public."subjects" force row level security;
create policy "branch_scope" on public."subjects" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."subjects" as permissive for all to academy_executor using (true) with check (true);
create policy "master_data_manage_subjects" on public."subjects" as permissive for all to authenticated using (has_permission('system.master_data.manage'::text)) with check (has_permission('system.master_data.manage'::text));
create policy "subjects_public_read" on public."subjects" as permissive for select to anon,authenticated using (is_active);
grant SELECT on public."subjects" to authenticated;
alter table public."system_roles" enable row level security;
create policy "executor_catalogue_read" on public."system_roles" as permissive for select to academy_executor using ((academy_private.current_branch_id() IS NOT NULL));
create policy "system_roles_read" on public."system_roles" as permissive for select to authenticated using (true);
grant SELECT on public."system_roles" to authenticated;
alter table public."user_role_assignments" enable row level security;
alter table public."user_role_assignments" force row level security;
create policy "branch_scope" on public."user_role_assignments" as restrictive for all to authenticated,academy_executor using ((scope_branch_id = academy_private.current_branch_id())) with check ((scope_branch_id = academy_private.current_branch_id()));
create policy "executor_workflows" on public."user_role_assignments" as permissive for all to academy_executor using (true) with check (true);
create policy "user_roles_admin_read" on public."user_role_assignments" as permissive for select to authenticated using (((profile_id = auth.uid()) OR has_permission('system.users.manage'::text)));
create policy "user_roles_admin_update" on public."user_role_assignments" as permissive for update to authenticated using (has_permission('system.users.manage'::text)) with check (has_permission('system.users.manage'::text));
create policy "user_roles_admin_write" on public."user_role_assignments" as permissive for insert to authenticated with check (has_permission('system.users.manage'::text));
grant SELECT on public."user_role_assignments" to authenticated;
alter function academic_command(jsonb) owner to academy_executor;
revoke all on function academic_command(jsonb) from public,anon,authenticated;
grant execute on function academic_command(jsonb) to academy_executor;
grant execute on function academic_command(jsonb) to authenticated;
alter function academic_workspace(date,date) owner to academy_executor;
revoke all on function academic_workspace(date,date) from public,anon,authenticated;
grant execute on function academic_workspace(date,date) to academy_executor;
grant execute on function academic_workspace(date,date) to authenticated;
alter function academy_setup_status() owner to academy_executor;
revoke all on function academy_setup_status() from public,anon,authenticated;
grant execute on function academy_setup_status() to academy_executor;
grant execute on function academy_setup_status() to authenticated;
alter function add_branch_member(text,text) owner to postgres;
revoke all on function add_branch_member(text,text) from public,anon,authenticated;
grant execute on function add_branch_member(text,text) to academy_executor;
grant execute on function add_branch_member(text,text) to authenticated;
alter function admission_case_detail(uuid) owner to academy_executor;
revoke all on function admission_case_detail(uuid) from public,anon,authenticated;
grant execute on function admission_case_detail(uuid) to academy_executor;
grant execute on function admission_case_detail(uuid) to authenticated;
alter function admission_command(jsonb) owner to academy_executor;
revoke all on function admission_command(jsonb) from public,anon,authenticated;
grant execute on function admission_command(jsonb) to academy_executor;
grant execute on function admission_command(jsonb) to authenticated;
alter function admission_directory_options() owner to academy_executor;
revoke all on function admission_directory_options() from public,anon,authenticated;
grant execute on function admission_directory_options() to academy_executor;
grant execute on function admission_directory_options() to authenticated;
alter function admission_offering_options() owner to academy_executor;
revoke all on function admission_offering_options() from public,anon,authenticated;
grant execute on function admission_offering_options() to academy_executor;
grant execute on function admission_offering_options() to authenticated;
alter function admission_workspace() owner to academy_executor;
revoke all on function admission_workspace() from public,anon,authenticated;
grant execute on function admission_workspace() to academy_executor;
grant execute on function admission_workspace() to authenticated;
alter function assessment_command(jsonb) owner to academy_executor;
revoke all on function assessment_command(jsonb) from public,anon,authenticated;
grant execute on function assessment_command(jsonb) to academy_executor;
grant execute on function assessment_command(jsonb) to authenticated;
alter function assessment_workspace() owner to academy_executor;
revoke all on function assessment_workspace() from public,anon,authenticated;
grant execute on function assessment_workspace() to academy_executor;
grant execute on function assessment_workspace() to authenticated;
alter function assign_prospect_staff(jsonb) owner to academy_executor;
revoke all on function assign_prospect_staff(jsonb) from public,anon,authenticated;
grant execute on function assign_prospect_staff(jsonb) to academy_executor;
grant execute on function assign_prospect_staff(jsonb) to authenticated;
alter function audit_event_list(uuid) owner to academy_executor;
revoke all on function audit_event_list(uuid) from public,anon,authenticated;
grant execute on function audit_event_list(uuid) to academy_executor;
grant execute on function audit_event_list(uuid) to authenticated;
alter function audit_event_page(jsonb) owner to academy_executor;
revoke all on function audit_event_page(jsonb) from public,anon,authenticated;
grant execute on function audit_event_page(jsonb) to academy_executor;
grant execute on function audit_event_page(jsonb) to authenticated;
alter function batch_command(jsonb) owner to academy_executor;
revoke all on function batch_command(jsonb) from public,anon,authenticated;
grant execute on function batch_command(jsonb) to academy_executor;
grant execute on function batch_command(jsonb) to authenticated;
alter function can_access_assessment(uuid,uuid) owner to academy_executor;
revoke all on function can_access_assessment(uuid,uuid) from public,anon,authenticated;
grant execute on function can_access_assessment(uuid,uuid) to academy_executor;
grant execute on function can_access_assessment(uuid,uuid) to authenticated;
alter function can_access_class_session(uuid) owner to academy_executor;
revoke all on function can_access_class_session(uuid) from public,anon,authenticated;
grant execute on function can_access_class_session(uuid) to academy_executor;
grant execute on function can_access_class_session(uuid) to authenticated;
alter function capture_audit_actor() owner to academy_executor;
revoke all on function capture_audit_actor() from public,anon,authenticated;
grant execute on function capture_audit_actor() to academy_executor;
alter function class_log_command(jsonb) owner to academy_executor;
revoke all on function class_log_command(jsonb) from public,anon,authenticated;
grant execute on function class_log_command(jsonb) to academy_executor;
grant execute on function class_log_command(jsonb) to authenticated;
alter function class_log_workspace(uuid) owner to academy_executor;
revoke all on function class_log_workspace(uuid) from public,anon,authenticated;
grant execute on function class_log_workspace(uuid) to academy_executor;
grant execute on function class_log_workspace(uuid) to authenticated;
alter function class_session_workspace(uuid) owner to academy_executor;
revoke all on function class_session_workspace(uuid) from public,anon,authenticated;
grant execute on function class_session_workspace(uuid) to academy_executor;
grant execute on function class_session_workspace(uuid) to authenticated;
alter function close_student_enrollment(jsonb) owner to academy_executor;
revoke all on function close_student_enrollment(jsonb) from public,anon,authenticated;
grant execute on function close_student_enrollment(jsonb) to academy_executor;
grant execute on function close_student_enrollment(jsonb) to authenticated;
alter function complete_academy_setup() owner to academy_executor;
revoke all on function complete_academy_setup() from public,anon,authenticated;
grant execute on function complete_academy_setup() to academy_executor;
grant execute on function complete_academy_setup() to authenticated;
alter function correct_admission_placement(jsonb) owner to academy_executor;
revoke all on function correct_admission_placement(jsonb) from public,anon,authenticated;
grant execute on function correct_admission_placement(jsonb) to academy_executor;
grant execute on function correct_admission_placement(jsonb) to authenticated;
alter function create_admission_directory_choice(jsonb) owner to academy_executor;
revoke all on function create_admission_directory_choice(jsonb) from public,anon,authenticated;
grant execute on function create_admission_directory_choice(jsonb) to academy_executor;
grant execute on function create_admission_directory_choice(jsonb) to authenticated;
alter function create_programme_offering(jsonb) owner to academy_executor;
revoke all on function create_programme_offering(jsonb) from public,anon,authenticated;
grant execute on function create_programme_offering(jsonb) to academy_executor;
grant execute on function create_programme_offering(jsonb) to authenticated;
alter function create_prospect_admission(jsonb) owner to academy_executor;
revoke all on function create_prospect_admission(jsonb) from public,anon,authenticated;
grant execute on function create_prospect_admission(jsonb) to academy_executor;
grant execute on function create_prospect_admission(jsonb) to authenticated;
alter function create_staff_admission_intake(jsonb) owner to academy_executor;
revoke all on function create_staff_admission_intake(jsonb) from public,anon,authenticated;
grant execute on function create_staff_admission_intake(jsonb) to academy_executor;
grant execute on function create_staff_admission_intake(jsonb) to authenticated;
alter function create_staff_member(jsonb) owner to academy_executor;
revoke all on function create_staff_member(jsonb) from public,anon,authenticated;
grant execute on function create_staff_member(jsonb) to academy_executor;
grant execute on function create_staff_member(jsonb) to authenticated;
alter function academy_private.current_branch_id() owner to postgres;
revoke all on function academy_private.current_branch_id() from public,anon,authenticated;
grant execute on function academy_private.current_branch_id() to academy_executor;
grant execute on function academy_private.current_branch_id() to anon;
grant execute on function academy_private.current_branch_id() to authenticated;
alter function edit_admission_identity(jsonb) owner to academy_executor;
revoke all on function edit_admission_identity(jsonb) from public,anon,authenticated;
grant execute on function edit_admission_identity(jsonb) to academy_executor;
grant execute on function edit_admission_identity(jsonb) to authenticated;
alter function edit_staff_record(jsonb) owner to academy_executor;
revoke all on function edit_staff_record(jsonb) from public,anon,authenticated;
grant execute on function edit_staff_record(jsonb) to academy_executor;
grant execute on function edit_staff_record(jsonb) to authenticated;
alter function enforce_approval_decision() owner to academy_executor;
revoke all on function enforce_approval_decision() from public,anon,authenticated;
grant execute on function enforce_approval_decision() to academy_executor;
alter function enforce_batch_policy() owner to academy_executor;
revoke all on function enforce_batch_policy() from public,anon,authenticated;
grant execute on function enforce_batch_policy() to academy_executor;
alter function enforce_enrollment_batch_integrity() owner to academy_executor;
revoke all on function enforce_enrollment_batch_integrity() from public,anon,authenticated;
grant execute on function enforce_enrollment_batch_integrity() to academy_executor;
alter function enforce_staff_subject_teaching_role() owner to academy_executor;
revoke all on function enforce_staff_subject_teaching_role() from public,anon,authenticated;
grant execute on function enforce_staff_subject_teaching_role() to academy_executor;
alter function guard_submitted_class_log() owner to academy_executor;
revoke all on function guard_submitted_class_log() from public,anon,authenticated;
grant execute on function guard_submitted_class_log() to academy_executor;
alter function has_permission(text) owner to postgres;
revoke all on function has_permission(text) from public,anon,authenticated;
grant execute on function has_permission(text) to academy_executor;
grant execute on function has_permission(text) to authenticated;
alter function homework_command(jsonb) owner to academy_executor;
revoke all on function homework_command(jsonb) from public,anon,authenticated;
grant execute on function homework_command(jsonb) to academy_executor;
grant execute on function homework_command(jsonb) to authenticated;
alter function homework_workspace(uuid) owner to academy_executor;
revoke all on function homework_workspace(uuid) from public,anon,authenticated;
grant execute on function homework_workspace(uuid) to academy_executor;
grant execute on function homework_workspace(uuid) to authenticated;
alter function academy_private.is_branch_member(uuid) owner to postgres;
revoke all on function academy_private.is_branch_member(uuid) from public,anon,authenticated;
grant execute on function academy_private.is_branch_member(uuid) to academy_executor;
grant execute on function academy_private.is_branch_member(uuid) to anon;
grant execute on function academy_private.is_branch_member(uuid) to authenticated;
alter function is_valid_prospect_transition(prospect_status,prospect_status) owner to academy_executor;
revoke all on function is_valid_prospect_transition(prospect_status,prospect_status) from public,anon,authenticated;
grant execute on function is_valid_prospect_transition(prospect_status,prospect_status) to academy_executor;
grant execute on function is_valid_prospect_transition(prospect_status,prospect_status) to authenticated;
alter function legacy_attendance_command(jsonb) owner to academy_executor;
revoke all on function legacy_attendance_command(jsonb) from public,anon,authenticated;
grant execute on function legacy_attendance_command(jsonb) to academy_executor;
alter function link_staff_profile_by_email(text) owner to academy_executor;
revoke all on function link_staff_profile_by_email(text) from public,anon,authenticated;
grant execute on function link_staff_profile_by_email(text) to academy_executor;
alter function list_my_branches() owner to postgres;
revoke all on function list_my_branches() from public,anon,authenticated;
grant execute on function list_my_branches() to academy_executor;
grant execute on function list_my_branches() to authenticated;
alter function list_public_programme_offerings() owner to postgres;
revoke all on function list_public_programme_offerings() from public,anon,authenticated;
grant execute on function list_public_programme_offerings() to academy_executor;
grant execute on function list_public_programme_offerings() to anon;
grant execute on function list_public_programme_offerings() to authenticated;
alter function manage_crm_master_record(jsonb) owner to academy_executor;
revoke all on function manage_crm_master_record(jsonb) from public,anon,authenticated;
grant execute on function manage_crm_master_record(jsonb) to academy_executor;
grant execute on function manage_crm_master_record(jsonb) to authenticated;
alter function my_erp_context() owner to academy_executor;
revoke all on function my_erp_context() from public,anon,authenticated;
grant execute on function my_erp_context() to academy_executor;
grant execute on function my_erp_context() to authenticated;
alter function open_academy_branch(uuid,text,text,text,boolean) owner to postgres;
revoke all on function open_academy_branch(uuid,text,text,text,boolean) from public,anon,authenticated;
grant execute on function open_academy_branch(uuid,text,text,text,boolean) to academy_executor;
grant execute on function open_academy_branch(uuid,text,text,text,boolean) to authenticated;
alter function prevent_permanent_record_delete() owner to academy_executor;
revoke all on function prevent_permanent_record_delete() from public,anon,authenticated;
grant execute on function prevent_permanent_record_delete() to academy_executor;
alter function prospect_assignment_options() owner to academy_executor;
revoke all on function prospect_assignment_options() from public,anon,authenticated;
grant execute on function prospect_assignment_options() to academy_executor;
grant execute on function prospect_assignment_options() to authenticated;
alter function protect_academic_record() owner to academy_executor;
revoke all on function protect_academic_record() from public,anon,authenticated;
grant execute on function protect_academic_record() to academy_executor;
alter function protect_active_business_rule() owner to academy_executor;
revoke all on function protect_active_business_rule() from public,anon,authenticated;
grant execute on function protect_active_business_rule() to academy_executor;
alter function protect_record_history() owner to academy_executor;
revoke all on function protect_record_history() from public,anon,authenticated;
grant execute on function protect_record_history() to academy_executor;
alter function academy_private.protect_branch_scope() owner to postgres;
revoke all on function academy_private.protect_branch_scope() from public,anon,authenticated;
grant execute on function academy_private.protect_branch_scope() to academy_executor;
grant execute on function academy_private.protect_branch_scope() to anon;
grant execute on function academy_private.protect_branch_scope() to authenticated;
alter function public_academic_directory() owner to postgres;
revoke all on function public_academic_directory() from public,anon,authenticated;
grant execute on function public_academic_directory() to academy_executor;
grant execute on function public_academic_directory() to anon;
grant execute on function public_academic_directory() to authenticated;
alter function academy_private.public_branch_id() owner to postgres;
revoke all on function academy_private.public_branch_id() from public,anon,authenticated;
grant execute on function academy_private.public_branch_id() to academy_executor;
grant execute on function academy_private.public_branch_id() to anon;
grant execute on function academy_private.public_branch_id() to authenticated;
alter function publish_business_rule_version(text,text,jsonb,text) owner to academy_executor;
revoke all on function publish_business_rule_version(text,text,jsonb,text) from public,anon,authenticated;
grant execute on function publish_business_rule_version(text,text,jsonb,text) to academy_executor;
grant execute on function publish_business_rule_version(text,text,jsonb,text) to authenticated;
alter function question_bank_command(jsonb) owner to academy_executor;
revoke all on function question_bank_command(jsonb) from public,anon,authenticated;
grant execute on function question_bank_command(jsonb) to academy_executor;
grant execute on function question_bank_command(jsonb) to authenticated;
alter function question_bank_workspace() owner to academy_executor;
revoke all on function question_bank_workspace() from public,anon,authenticated;
grant execute on function question_bank_workspace() to academy_executor;
grant execute on function question_bank_workspace() to authenticated;
alter function record_lifecycle_command(jsonb) owner to academy_executor;
revoke all on function record_lifecycle_command(jsonb) from public,anon,authenticated;
grant execute on function record_lifecycle_command(jsonb) to academy_executor;
grant execute on function record_lifecycle_command(jsonb) to authenticated;
alter function record_physical_admission_consent(jsonb) owner to academy_executor;
revoke all on function record_physical_admission_consent(jsonb) from public,anon,authenticated;
grant execute on function record_physical_admission_consent(jsonb) to academy_executor;
grant execute on function record_physical_admission_consent(jsonb) to authenticated;
alter function record_prospect_followup(jsonb) owner to academy_executor;
revoke all on function record_prospect_followup(jsonb) from public,anon,authenticated;
grant execute on function record_prospect_followup(jsonb) to academy_executor;
grant execute on function record_prospect_followup(jsonb) to authenticated;
alter function remove_branch_member(text) owner to postgres;
revoke all on function remove_branch_member(text) from public,anon,authenticated;
grant execute on function remove_branch_member(text) to academy_executor;
grant execute on function remove_branch_member(text) to authenticated;
alter function save_academy_identity(jsonb) owner to postgres;
revoke all on function save_academy_identity(jsonb) from public,anon,authenticated;
grant execute on function save_academy_identity(jsonb) to academy_executor;
grant execute on function save_academy_identity(jsonb) to authenticated;
alter function set_updated_at() owner to academy_executor;
revoke all on function set_updated_at() from public,anon,authenticated;
grant execute on function set_updated_at() to academy_executor;
alter function staff_link_profile_trigger() owner to academy_executor;
revoke all on function staff_link_profile_trigger() from public,anon,authenticated;
grant execute on function staff_link_profile_trigger() to academy_executor;
alter function staff_task_command(jsonb) owner to academy_executor;
revoke all on function staff_task_command(jsonb) from public,anon,authenticated;
grant execute on function staff_task_command(jsonb) to academy_executor;
grant execute on function staff_task_command(jsonb) to authenticated;
alter function staff_tasks_workspace(uuid,boolean,integer) owner to academy_executor;
revoke all on function staff_tasks_workspace(uuid,boolean,integer) from public,anon,authenticated;
grant execute on function staff_tasks_workspace(uuid,boolean,integer) to academy_executor;
grant execute on function staff_tasks_workspace(uuid,boolean,integer) to authenticated;
alter function staff_work_workspace(date,uuid,integer) owner to academy_executor;
revoke all on function staff_work_workspace(date,uuid,integer) from public,anon,authenticated;
grant execute on function staff_work_workspace(date,uuid,integer) to academy_executor;
grant execute on function staff_work_workspace(date,uuid,integer) to authenticated;
alter function student_command(jsonb) owner to academy_executor;
revoke all on function student_command(jsonb) from public,anon,authenticated;
grant execute on function student_command(jsonb) to academy_executor;
grant execute on function student_command(jsonb) to authenticated;
alter function student_profile_workspace(uuid) owner to academy_executor;
revoke all on function student_profile_workspace(uuid) from public,anon,authenticated;
grant execute on function student_profile_workspace(uuid) to academy_executor;
grant execute on function student_profile_workspace(uuid) to authenticated;
alter function submit_public_interest(jsonb) owner to postgres;
revoke all on function submit_public_interest(jsonb) from public,anon,authenticated;
grant execute on function submit_public_interest(jsonb) to academy_executor;
grant execute on function submit_public_interest(jsonb) to anon;
grant execute on function submit_public_interest(jsonb) to authenticated;
alter function sync_admission_student_details() owner to academy_executor;
revoke all on function sync_admission_student_details() from public,anon,authenticated;
grant execute on function sync_admission_student_details() to academy_executor;
alter function sync_student_optional_contact() owner to academy_executor;
revoke all on function sync_student_optional_contact() from public,anon,authenticated;
grant execute on function sync_student_optional_contact() to academy_executor;
alter function update_programme_offering(jsonb) owner to academy_executor;
revoke all on function update_programme_offering(jsonb) from public,anon,authenticated;
grant execute on function update_programme_offering(jsonb) to academy_executor;
grant execute on function update_programme_offering(jsonb) to authenticated;
alter function update_programme_offering_public_controls(jsonb) owner to academy_executor;
revoke all on function update_programme_offering_public_controls(jsonb) from public,anon,authenticated;
grant execute on function update_programme_offering_public_controls(jsonb) to academy_executor;
grant execute on function update_programme_offering_public_controls(jsonb) to authenticated;
alter function validate_business_rule_payload(text,text,jsonb) owner to academy_executor;
revoke all on function validate_business_rule_payload(text,text,jsonb) from public,anon,authenticated;
grant execute on function validate_business_rule_payload(text,text,jsonb) to academy_executor;
grant execute on function validate_business_rule_payload(text,text,jsonb) to authenticated;
alter function workforce_command(jsonb) owner to academy_executor;
revoke all on function workforce_command(jsonb) from public,anon,authenticated;
grant execute on function workforce_command(jsonb) to academy_executor;
grant execute on function workforce_command(jsonb) to authenticated;
CREATE TRIGGER academic_immutable BEFORE DELETE OR UPDATE ON class_sessions FOR EACH ROW EXECUTE FUNCTION protect_academic_record();
CREATE TRIGGER academic_immutable BEFORE DELETE OR UPDATE ON attendance_submissions FOR EACH ROW EXECUTE FUNCTION protect_academic_record();
CREATE TRIGGER academic_immutable BEFORE DELETE OR UPDATE ON academic_rooms FOR EACH ROW EXECUTE FUNCTION protect_record_history();
CREATE TRIGGER academic_immutable BEFORE DELETE OR UPDATE ON curriculum_versions FOR EACH ROW EXECUTE FUNCTION protect_record_history();
CREATE TRIGGER academic_immutable BEFORE DELETE OR UPDATE ON academic_routines FOR EACH ROW EXECUTE FUNCTION protect_academic_record();
CREATE TRIGGER admission_student_contact AFTER UPDATE OF student_id, identity_snapshot ON admission_cases FOR EACH ROW EXECUTE FUNCTION sync_student_optional_contact();
CREATE TRIGGER admission_student_details_sync AFTER UPDATE OF student_id ON admission_cases FOR EACH ROW EXECUTE FUNCTION sync_admission_student_details();
CREATE TRIGGER admission_updated BEFORE UPDATE ON admission_cases FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER approval_requests_decision_guard BEFORE UPDATE OF status ON approval_requests FOR EACH ROW EXECUTE FUNCTION enforce_approval_decision();
CREATE TRIGGER attendance_no_delete BEFORE DELETE ON staff_attendance_records FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER batches_capacity_policy BEFORE INSERT OR UPDATE OF capacity ON batches FOR EACH ROW EXECUTE FUNCTION enforce_batch_policy();
CREATE TRIGGER batches_set_updated_at BEFORE UPDATE ON batches FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER branches_set_updated_at BEFORE UPDATE ON branches FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER business_rule_version_guard BEFORE DELETE OR UPDATE ON business_rule_versions FOR EACH ROW EXECUTE FUNCTION protect_active_business_rule();
CREATE TRIGGER capture_audit_identity BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION capture_audit_actor();
CREATE TRIGGER class_log_history_guard BEFORE DELETE OR UPDATE ON class_logs FOR EACH ROW EXECUTE FUNCTION guard_submitted_class_log();
CREATE TRIGGER enrollments_batch_integrity BEFORE INSERT OR UPDATE OF batch_id, status, academic_year_id, class_id, program_id ON enrollments FOR EACH ROW EXECUTE FUNCTION enforce_enrollment_batch_integrity();
CREATE TRIGGER enrollments_set_updated_at BEFORE UPDATE ON enrollments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER guardians_set_updated_at BEFORE UPDATE ON guardians FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER lifecycle_immutable BEFORE DELETE OR UPDATE ON student_merges FOR EACH ROW EXECUTE FUNCTION protect_record_history();
CREATE TRIGGER lifecycle_immutable BEFORE DELETE OR UPDATE ON enrollment_transfers FOR EACH ROW EXECUTE FUNCTION protect_record_history();
CREATE TRIGGER organizations_set_updated_at BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON programs FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON organizations FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON branches FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON profiles FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON staff FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON schools FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON academic_years FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON classes FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON academic_groups FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON subjects FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON students FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON guardians FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON prospects FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON batches FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON enrollments FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON admission_cases FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON admission_physical_consent_receipts FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER preserve_permanent_record BEFORE DELETE ON staff_access_requests FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();
CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER programme_offerings_set_updated_at BEFORE UPDATE ON programme_offerings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER prospects_set_updated_at BEFORE UPDATE ON prospects FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON staff_attendance_records FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON staff_work_tasks FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON programme_offering_subjects FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON students FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON staff_access_requests FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON academic_rooms FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON attendance_submissions FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON curriculum_versions FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON academic_routines FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON class_sessions FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON admission_physical_consent_receipts FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON admission_command_keys FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON class_logs FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON question_bank_items FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON homework_checks FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON academic_assessments FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON assessment_result_submissions FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON staff_admission_intake_requests FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON audit_events FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON staff_role_assignments FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON academic_years FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON classes FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON programs FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON subjects FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON areas FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON schools FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON lead_sources FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON guardian_relationships FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON staff FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON student_guardians FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON prospect_program_interests FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON prospect_subject_interests FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON staff_subject_assignments FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON prospect_followups FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON prospects FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON guardians FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON business_rule_versions FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON user_role_assignments FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON academic_groups FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON programme_offerings FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON batches FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON enrollments FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON admission_cases FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON approval_requests FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON student_merges FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER protect_branch_scope BEFORE INSERT OR UPDATE ON enrollment_transfers FOR EACH ROW EXECUTE FUNCTION academy_private.protect_branch_scope();
CREATE TRIGGER schools_set_updated_at BEFORE UPDATE ON schools FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER staff_link_profile AFTER INSERT OR UPDATE OF email, status ON staff FOR EACH ROW WHEN (new.profile_id IS NULL AND new.email IS NOT NULL) EXECUTE FUNCTION staff_link_profile_trigger();
CREATE TRIGGER staff_set_updated_at BEFORE UPDATE ON staff FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER staff_subject_requires_teaching_role BEFORE INSERT OR UPDATE OF staff_id, subject_id, effective_to ON staff_subject_assignments FOR EACH ROW EXECUTE FUNCTION enforce_staff_subject_teaching_role();
CREATE TRIGGER students_set_updated_at BEFORE UPDATE ON students FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER work_tasks_no_delete BEFORE DELETE ON staff_work_tasks FOR EACH ROW EXECUTE FUNCTION prevent_permanent_record_delete();

alter function public.generate_staff_no() owner to postgres;

alter function public.generate_student_no() owner to postgres;

alter function public.generate_prospect_no() owner to postgres;

alter function public.admin_review_queue() owner to academy_executor;
revoke all on function public.admin_review_queue() from public,anon;
grant execute on function public.admin_review_queue() to authenticated;

revoke all on function public.generate_prospect_no() from public,anon;
grant execute on function public.generate_prospect_no() to authenticated,academy_executor;

revoke all on function public.generate_staff_no() from public,anon;
grant execute on function public.generate_staff_no() to authenticated,academy_executor;

revoke all on function public.generate_student_no() from public,anon;
grant execute on function public.generate_student_no() to authenticated,academy_executor;
