'use client';
import Link from 'next/link';
import { useState } from 'react';
import { createClient } from '@/lib/supabase/client';
export function AuthForm({ signup=false, confirmationError=false }:{signup?:boolean; confirmationError?:boolean}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState(confirmationError?'Confirmation link invalid or expired. Sign in or request a new email.':''),[message,setMessage]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setMessage('');const form=new FormData(event.currentTarget);
 try {const db=createClient();const email=String(form.get('email')).trim(),password=String(form.get('password'));
 if(signup){const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth/confirm`}});if(error)throw error;if(data.session){window.location.assign('/onboarding');return;}setMessage('ইমেইলে confirmation link দেখুন। Confirm করে sign in করুন।');}
 else{const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;window.location.assign('/dashboard');return;}
 }catch{setError(signup?'অ্যাকাউন্ট তৈরি নিশ্চিত করা যায়নি। Email ও password যাচাই করুন অথবা বিদ্যমান account দিয়ে sign in করুন।':'Sign in হয়নি। Email, password ও email confirmation যাচাই করুন।');}finally{setBusy(false);}}
 return <main className="mx-auto max-w-md px-5 py-12"><Link href="/" className="text-xl font-bold">Outlinerz</Link><h1 className="mt-10 text-3xl font-bold">{signup?'Owner account তৈরি করুন':'Sign in'}</h1><p className="my-5 text-muted-foreground">{signup?'Account তৈরি করে নিজের প্রতিষ্ঠান শুরু করুন।':'আপনার প্রতিষ্ঠানের account দিয়ে প্রবেশ করুন।'}</p><form onSubmit={submit} className="space-y-5"><label className="block space-y-2"><span>Email</span><input name="email" type="email" autoComplete="email" required disabled={busy} className="w-full rounded-xl border bg-background p-3"/></label><label className="block space-y-2"><span>Password</span><input name="password" type="password" minLength={signup?8:undefined} autoComplete={signup?'new-password':'current-password'} required disabled={busy} className="w-full rounded-xl border bg-background p-3"/></label><div aria-live="polite">{error&&<p role="alert" className="text-sm text-red-400">{error}</p>}{message&&<p className="text-sm text-emerald-400">{message}</p>}</div><button disabled={busy} className="w-full rounded-xl bg-primary p-3 font-semibold text-primary-foreground disabled:opacity-50">{busy?'অপেক্ষা করুন…':signup?'Create account':'Sign in'}</button></form><Link className="mt-6 block underline" href={signup?'/auth/sign-in':'/auth/sign-up'}>{signup?'Already have an account? Sign in':'Create an owner account'}</Link>{!signup&&<Link href="/auth/forgot-password" className="mt-3 block underline">Forgot password?</Link>}</main>;
}
